/* ────────────────────────────────────────────────────────────────────────────
   PeakForm Bio — Food database  (~530 items)
   USDA FoodData Central-style values.
   Fields: id, name, cat, qty, unit, kcal, p (protein g), c (carbs g), f (fat g)
   ──────────────────────────────────────────────────────────────────────────── */
(function () {
  window.FOOD_CATEGORIES = [
    'Eggs', 'Protein', 'Carbs & Grains', 'Vegetables',
    'Fruit', 'Dairy & Eggs', 'Fats & Nuts', 'Legumes',
    'Beverages', 'Condiments', 'Snacks', 'Fast Food',
    'Meals & Prepared', 'International', 'Brands',
  ];

  const F = [
    /* ─── Eggs ─────────────────────────────────────────────────────── */
    { name:'Egg, whole (large)',           cat:'Eggs', qty:1,    unit:'large egg (50g)',    kcal:72,  p:6,    c:0.4, f:5    },
    { name:'Egg, whole (medium)',          cat:'Eggs', qty:1,    unit:'medium egg (44g)',   kcal:63,  p:5.5,  c:0.3, f:4.4  },
    { name:'Egg, whole (extra-large)',     cat:'Eggs', qty:1,    unit:'XL egg (56g)',       kcal:80,  p:7,    c:0.4, f:5.6  },
    { name:'Egg white (large)',            cat:'Eggs', qty:1,    unit:'white (33g)',        kcal:17,  p:3.6,  c:0.2, f:0    },
    { name:'Egg yolk (large)',             cat:'Eggs', qty:1,    unit:'yolk (17g)',         kcal:55,  p:2.7,  c:0.6, f:4.5  },
    { name:'Egg, hard-boiled',            cat:'Eggs', qty:1,    unit:'large egg (50g)',    kcal:78,  p:6.3,  c:0.6, f:5.3  },
    { name:'Egg, soft-boiled',            cat:'Eggs', qty:1,    unit:'large egg (50g)',    kcal:72,  p:6.3,  c:0.4, f:5    },
    { name:'Egg, poached',                cat:'Eggs', qty:1,    unit:'large egg (50g)',    kcal:71,  p:6.2,  c:0.4, f:4.9  },
    { name:'Egg, fried (no added oil)',   cat:'Eggs', qty:1,    unit:'large egg (46g)',    kcal:90,  p:6.3,  c:0.4, f:7    },
    { name:'Egg, over-easy (with oil)',   cat:'Eggs', qty:1,    unit:'large egg (48g)',    kcal:107, p:6.3,  c:0.4, f:9    },
    { name:'Eggs, scrambled (plain)',     cat:'Eggs', qty:2,    unit:'large eggs (122g)',  kcal:182, p:12,   c:3.2, f:13   },
    { name:'Eggs, scrambled w/ milk',     cat:'Eggs', qty:2,    unit:'large eggs (131g)',  kcal:204, p:14,   c:3.5, f:15   },
    { name:'Egg whites, liquid',          cat:'Eggs', qty:1,    unit:'cup (243g)',         kcal:117, p:26,   c:2,   f:0.4  },
    { name:'Egg substitute (Egg Beaters)',cat:'Eggs', qty:0.25, unit:'cup (61g)',          kcal:25,  p:5,    c:0.5, f:0    },
    { name:'Omelet, 2-egg plain',         cat:'Eggs', qty:1,    unit:'omelet (94g)',       kcal:187, p:13,   c:0.8, f:15   },
    { name:'Eggs, by weight',             cat:'Eggs', qty:100,  unit:'g',                  kcal:143, p:12.6, c:0.7, f:9.5  },
    { name:'Deviled eggs (2 halves)',      cat:'Eggs', qty:2,    unit:'halves (70g)',       kcal:122, p:6.5,  c:1,   f:10   },

    /* ─── Protein — Poultry ─────────────────────────────────────────── */
    { name:'Chicken breast, grilled',              cat:'Protein', qty:100, unit:'g', kcal:165, p:31,  c:0, f:3.6 },
    { name:'Chicken breast, raw',                  cat:'Protein', qty:100, unit:'g', kcal:120, p:22,  c:0, f:2.6 },
    { name:'Chicken breast, baked',                cat:'Protein', qty:100, unit:'g', kcal:165, p:31,  c:0, f:3.6 },
    { name:'Chicken breast, pan-seared',           cat:'Protein', qty:100, unit:'g', kcal:173, p:31,  c:0, f:4.5 },
    { name:'Chicken thigh, boneless, grilled',     cat:'Protein', qty:100, unit:'g', kcal:177, p:22,  c:0, f:9.5 },
    { name:'Chicken thigh, bone-in, roasted',      cat:'Protein', qty:100, unit:'g', kcal:209, p:26,  c:0, f:11  },
    { name:'Chicken drumstick, roasted',           cat:'Protein', qty:1,   unit:'drumstick (52g)', kcal:112, p:14, c:0, f:6 },
    { name:'Chicken wing, cooked',                 cat:'Protein', qty:1,   unit:'wing (34g)',      kcal:99,  p:9,  c:0, f:7 },
    { name:'Rotisserie chicken breast',            cat:'Protein', qty:100, unit:'g', kcal:185, p:29,  c:0, f:7   },
    { name:'Rotisserie chicken thigh',             cat:'Protein', qty:100, unit:'g', kcal:192, p:22,  c:0, f:11  },
    { name:'Ground chicken, cooked',               cat:'Protein', qty:100, unit:'g', kcal:170, p:22,  c:0, f:9   },
    { name:'Chicken tenders, baked',               cat:'Protein', qty:100, unit:'g', kcal:162, p:26,  c:5, f:4.5 },
    { name:'Chicken nuggets (fast food style)',    cat:'Protein', qty:6,   unit:'pieces (99g)',    kcal:280, p:13, c:18, f:16 },
    { name:'Turkey breast, roasted',               cat:'Protein', qty:100, unit:'g', kcal:135, p:30,  c:0, f:1   },
    { name:'Turkey breast, deli sliced',           cat:'Protein', qty:1,   unit:'oz (28g)',        kcal:30,  p:5,  c:0.5, f:0.6 },
    { name:'Ground turkey 93/7, cooked',           cat:'Protein', qty:100, unit:'g', kcal:149, p:24,  c:0, f:5   },
    { name:'Ground turkey 99% lean, cooked',       cat:'Protein', qty:100, unit:'g', kcal:120, p:26,  c:0, f:1.5 },
    { name:'Turkey bacon',                         cat:'Protein', qty:2,   unit:'slices (28g)',    kcal:60,  p:4,  c:1,   f:4.5 },
    { name:'Turkey sausage, cooked',               cat:'Protein', qty:1,   unit:'link (56g)',      kcal:111, p:12, c:2,   f:6   },
    { name:'Duck breast, cooked',                  cat:'Protein', qty:100, unit:'g', kcal:201, p:28,  c:0, f:10  },

    /* ─── Protein — Beef ────────────────────────────────────────────── */
    { name:'Lean ground beef 93/7, cooked',  cat:'Protein', qty:100, unit:'g', kcal:182, p:25, c:0, f:9  },
    { name:'Ground beef 85/15, cooked',      cat:'Protein', qty:100, unit:'g', kcal:215, p:26, c:0, f:12 },
    { name:'Ground beef 80/20, cooked',      cat:'Protein', qty:100, unit:'g', kcal:254, p:26, c:0, f:16 },
    { name:'Beef burger patty (1/4 lb)',     cat:'Protein', qty:1,   unit:'patty (113g)',    kcal:287, p:21, c:0, f:22 },
    { name:'Sirloin steak, grilled',         cat:'Protein', qty:100, unit:'g', kcal:207, p:29, c:0, f:9  },
    { name:'Ribeye steak, grilled',          cat:'Protein', qty:100, unit:'g', kcal:291, p:24, c:0, f:21 },
    { name:'NY strip steak, grilled',        cat:'Protein', qty:100, unit:'g', kcal:207, p:30, c:0, f:9  },
    { name:'Flank steak, grilled',           cat:'Protein', qty:100, unit:'g', kcal:194, p:26, c:0, f:9  },
    { name:'Skirt steak, grilled',           cat:'Protein', qty:100, unit:'g', kcal:204, p:26, c:0, f:11 },
    { name:'T-bone steak, grilled',          cat:'Protein', qty:100, unit:'g', kcal:247, p:24, c:0, f:16 },
    { name:'Beef tenderloin (filet)',         cat:'Protein', qty:100, unit:'g', kcal:185, p:29, c:0, f:8  },
    { name:'Chuck roast, braised',           cat:'Protein', qty:100, unit:'g', kcal:253, p:26, c:0, f:16 },
    { name:'Beef brisket, braised',          cat:'Protein', qty:100, unit:'g', kcal:253, p:27, c:0, f:16 },
    { name:'Beef short ribs, braised',       cat:'Protein', qty:100, unit:'g', kcal:381, p:18, c:0, f:34 },
    { name:'Beef meatballs, cooked',         cat:'Protein', qty:3,   unit:'meatballs (85g)', kcal:220, p:16, c:5, f:15 },
    { name:'Corned beef, cooked',            cat:'Protein', qty:100, unit:'g', kcal:251, p:18, c:0, f:19 },
    { name:'Bison, ground, cooked',          cat:'Protein', qty:100, unit:'g', kcal:179, p:26, c:0, f:8  },
    { name:'Beef liver, cooked',             cat:'Protein', qty:100, unit:'g', kcal:175, p:27, c:5, f:5  },
    { name:'Veal loin, roasted',             cat:'Protein', qty:100, unit:'g', kcal:196, p:28, c:0, f:9  },

    /* ─── Protein — Pork ────────────────────────────────────────────── */
    { name:'Pork tenderloin, roasted',   cat:'Protein', qty:100, unit:'g',           kcal:143, p:26, c:0, f:4   },
    { name:'Pork chop, grilled',         cat:'Protein', qty:100, unit:'g',           kcal:231, p:26, c:0, f:14  },
    { name:'Pork loin, roasted',         cat:'Protein', qty:100, unit:'g',           kcal:182, p:26, c:0, f:8   },
    { name:'Pork shoulder, roasted',     cat:'Protein', qty:100, unit:'g',           kcal:249, p:24, c:0, f:16  },
    { name:'Pulled pork, cooked',        cat:'Protein', qty:100, unit:'g',           kcal:240, p:22, c:5, f:15  },
    { name:'Pork ribs, back, cooked',    cat:'Protein', qty:100, unit:'g',           kcal:321, p:19, c:0, f:27  },
    { name:'Pork belly, braised',        cat:'Protein', qty:100, unit:'g',           kcal:518, p:9,  c:0, f:53  },
    { name:'Ground pork, cooked',        cat:'Protein', qty:100, unit:'g',           kcal:297, p:22, c:0, f:22  },
    { name:'Ham, cooked',                cat:'Protein', qty:100, unit:'g',           kcal:163, p:21, c:0, f:8   },
    { name:'Bacon, cooked',              cat:'Protein', qty:1,   unit:'slice (8g)',  kcal:43,  p:3,  c:0, f:3.3 },
    { name:'Canadian bacon',             cat:'Protein', qty:1,   unit:'slice (23g)', kcal:30,  p:5,  c:0.5, f:1 },
    { name:'Deli ham',                   cat:'Protein', qty:1,   unit:'oz (28g)',    kcal:35,  p:5,  c:0.8, f:1.2},
    { name:'Prosciutto, cured',          cat:'Protein', qty:1,   unit:'oz (28g)',    kcal:70,  p:8,  c:0,   f:4  },
    { name:'Chorizo, cooked',            cat:'Protein', qty:1,   unit:'oz (28g)',    kcal:129, p:7,  c:0,   f:11 },
    { name:'Italian sausage, cooked',    cat:'Protein', qty:1,   unit:'link (82g)',  kcal:230, p:15, c:4,   f:17 },
    { name:'Bratwurst, cooked',          cat:'Protein', qty:1,   unit:'link (85g)',  kcal:283, p:12, c:2,   f:25 },
    { name:'Hot dog (beef)',             cat:'Protein', qty:1,   unit:'frank (57g)', kcal:185, p:7,  c:2,   f:17 },
    { name:'Kielbasa, cooked',           cat:'Protein', qty:2,   unit:'oz (56g)',    kcal:180, p:8,  c:1,   f:16 },

    /* ─── Protein — Deli & Processed ───────────────────────────────── */
    { name:'Pepperoni, sliced',  cat:'Protein', qty:5,  unit:'slices (14g)', kcal:70,  p:3,   c:0.5, f:6   },
    { name:'Salami, sliced',     cat:'Protein', qty:1,  unit:'oz (28g)',     kcal:119, p:7,   c:0.5, f:10  },
    { name:'Bologna',            cat:'Protein', qty:1,  unit:'slice (28g)',  kcal:89,  p:4,   c:1,   f:8   },
    { name:'Pastrami',           cat:'Protein', qty:1,  unit:'oz (28g)',     kcal:41,  p:5.8, c:0.3, f:1.8 },
    { name:'Deli roast beef',    cat:'Protein', qty:1,  unit:'oz (28g)',     kcal:38,  p:6,   c:0.5, f:1.1 },
    { name:'Liverwurst',         cat:'Protein', qty:1,  unit:'oz (28g)',     kcal:92,  p:4,   c:1,   f:8   },
    { name:'Summer sausage',     cat:'Protein', qty:1,  unit:'oz (28g)',     kcal:100, p:5,   c:0.5, f:8.5 },

    /* ─── Protein — Seafood ─────────────────────────────────────────── */
    { name:'Salmon, baked',               cat:'Protein', qty:100, unit:'g', kcal:208, p:22,  c:0,   f:13  },
    { name:'Salmon, wild-caught, baked',  cat:'Protein', qty:100, unit:'g', kcal:177, p:25,  c:0,   f:8   },
    { name:'Atlantic salmon, raw',        cat:'Protein', qty:100, unit:'g', kcal:142, p:20,  c:0,   f:6   },
    { name:'Tuna, canned in water',       cat:'Protein', qty:100, unit:'g', kcal:116, p:26,  c:0,   f:1   },
    { name:'Tuna, canned in oil',         cat:'Protein', qty:100, unit:'g', kcal:198, p:29,  c:0,   f:9   },
    { name:'Tuna steak, grilled',         cat:'Protein', qty:100, unit:'g', kcal:144, p:30,  c:0,   f:2.5 },
    { name:'Tilapia, baked',              cat:'Protein', qty:100, unit:'g', kcal:128, p:26,  c:0,   f:3   },
    { name:'Cod, baked',                  cat:'Protein', qty:100, unit:'g', kcal:105, p:23,  c:0,   f:1   },
    { name:'Shrimp, cooked',              cat:'Protein', qty:100, unit:'g', kcal:99,  p:24,  c:0,   f:0.3 },
    { name:'Mahi-mahi, cooked',           cat:'Protein', qty:100, unit:'g', kcal:109, p:24,  c:0,   f:1   },
    { name:'Halibut, baked',              cat:'Protein', qty:100, unit:'g', kcal:111, p:23,  c:0,   f:2.3 },
    { name:'Swordfish, grilled',          cat:'Protein', qty:100, unit:'g', kcal:155, p:25,  c:0,   f:5   },
    { name:'Sardines, canned in oil',     cat:'Protein', qty:100, unit:'g', kcal:208, p:24,  c:0,   f:11  },
    { name:'Smoked salmon (lox)',         cat:'Protein', qty:1,   unit:'oz (28g)',      kcal:33,  p:5.2, c:0,   f:1.2 },
    { name:'Crab meat, cooked',           cat:'Protein', qty:100, unit:'g', kcal:97,  p:19,  c:0,   f:1.5 },
    { name:'Lobster, cooked',             cat:'Protein', qty:100, unit:'g', kcal:97,  p:20,  c:1.3, f:0.6 },
    { name:'Scallops, cooked',            cat:'Protein', qty:100, unit:'g', kcal:111, p:23,  c:1.4, f:0.8 },
    { name:'Oysters, cooked',             cat:'Protein', qty:6,   unit:'medium (87g)', kcal:70,  p:8,   c:4,   f:2   },
    { name:'Clams, steamed',              cat:'Protein', qty:3,   unit:'oz (85g)',      kcal:88,  p:15,  c:3,   f:1.2 },
    { name:'Mussels, cooked',             cat:'Protein', qty:3,   unit:'oz (85g)',      kcal:73,  p:10,  c:3,   f:2   },
    { name:'Rainbow trout, cooked',       cat:'Protein', qty:100, unit:'g', kcal:151, p:22,  c:0,   f:6.7 },
    { name:'Catfish, baked',              cat:'Protein', qty:100, unit:'g', kcal:144, p:18,  c:0,   f:7.6 },
    { name:'Sea bass, cooked',            cat:'Protein', qty:100, unit:'g', kcal:124, p:24,  c:0,   f:2.6 },
    { name:'Mackerel, cooked',            cat:'Protein', qty:100, unit:'g', kcal:262, p:24,  c:0,   f:18  },
    { name:'Anchovies, canned',           cat:'Protein', qty:1,   unit:'oz (28g)',      kcal:42,  p:6.5, c:0,   f:1.9 },
    { name:'Fish sticks, baked',          cat:'Protein', qty:3,   unit:'sticks (85g)', kcal:226, p:13,  c:19,  f:10  },
    { name:'Whey protein powder',         cat:'Protein', qty:1,   unit:'scoop (30g)',   kcal:120, p:24,  c:3,   f:1.5 },
    { name:'Casein protein powder',       cat:'Protein', qty:1,   unit:'scoop (33g)',   kcal:120, p:24,  c:4,   f:1   },
    { name:'Plant-based protein powder',  cat:'Protein', qty:1,   unit:'scoop (33g)',   kcal:130, p:22,  c:6,   f:3   },

    /* ─── Carbs & Grains — Rice & Grains ───────────────────────────── */
    { name:'White rice, cooked',       cat:'Carbs & Grains', qty:1,   unit:'cup (158g)', kcal:205, p:4,   c:45, f:0.4 },
    { name:'Brown rice, cooked',       cat:'Carbs & Grains', qty:1,   unit:'cup (195g)', kcal:218, p:5,   c:46, f:1.6 },
    { name:'Jasmine rice, cooked',     cat:'Carbs & Grains', qty:1,   unit:'cup (158g)', kcal:205, p:4,   c:45, f:0.4 },
    { name:'Basmati rice, cooked',     cat:'Carbs & Grains', qty:1,   unit:'cup (163g)', kcal:210, p:4,   c:46, f:0.4 },
    { name:'Wild rice, cooked',        cat:'Carbs & Grains', qty:1,   unit:'cup (164g)', kcal:166, p:6.5, c:35, f:0.6 },
    { name:'Cauliflower rice, cooked', cat:'Carbs & Grains', qty:1,   unit:'cup (107g)', kcal:27,  p:2,   c:5,  f:0.3 },
    { name:'Oats, dry',                cat:'Carbs & Grains', qty:0.5, unit:'cup (40g)',  kcal:150, p:5,   c:27, f:3   },
    { name:'Oatmeal, cooked',          cat:'Carbs & Grains', qty:1,   unit:'cup (234g)', kcal:166, p:5.9, c:28, f:3.6 },
    { name:'Quinoa, cooked',           cat:'Carbs & Grains', qty:1,   unit:'cup (185g)', kcal:222, p:8,   c:39, f:3.6 },
    { name:'Bulgur wheat, cooked',     cat:'Carbs & Grains', qty:1,   unit:'cup (182g)', kcal:151, p:5.6, c:34, f:0.4 },
    { name:'Farro, cooked',            cat:'Carbs & Grains', qty:1,   unit:'cup (200g)', kcal:220, p:8,   c:46, f:1.5 },
    { name:'Barley, cooked',           cat:'Carbs & Grains', qty:1,   unit:'cup (157g)', kcal:193, p:3.5, c:44, f:0.7 },
    { name:'Couscous, cooked',         cat:'Carbs & Grains', qty:1,   unit:'cup (157g)', kcal:176, p:6,   c:36, f:0.3 },
    { name:'Polenta, cooked',          cat:'Carbs & Grains', qty:1,   unit:'cup (240g)', kcal:145, p:3.5, c:31, f:0.5 },
    { name:'Millet, cooked',           cat:'Carbs & Grains', qty:1,   unit:'cup (174g)', kcal:207, p:6,   c:41, f:1.7 },
    { name:'Buckwheat groats, cooked', cat:'Carbs & Grains', qty:1,   unit:'cup (168g)', kcal:155, p:5.7, c:33, f:1   },
    { name:'Cream of rice, cooked',    cat:'Carbs & Grains', qty:1,   unit:'cup (245g)', kcal:127, p:2,   c:28, f:0.2 },
    { name:'Cream of Wheat, cooked',   cat:'Carbs & Grains', qty:1,   unit:'cup (242g)', kcal:133, p:4,   c:28, f:0.5 },
    { name:'Grits, cooked',            cat:'Carbs & Grains', qty:1,   unit:'cup (242g)', kcal:182, p:4.3, c:38, f:1   },

    /* ─── Carbs & Grains — Pasta & Noodles ─────────────────────────── */
    { name:'Spaghetti, cooked',           cat:'Carbs & Grains', qty:1, unit:'cup (140g)',  kcal:220, p:8,   c:43, f:1.3 },
    { name:'Penne, cooked',               cat:'Carbs & Grains', qty:1, unit:'cup (148g)',  kcal:220, p:8,   c:43, f:1.3 },
    { name:'Fettuccine, cooked',          cat:'Carbs & Grains', qty:1, unit:'cup (140g)',  kcal:220, p:8,   c:43, f:1.3 },
    { name:'Whole wheat pasta, cooked',   cat:'Carbs & Grains', qty:1, unit:'cup (140g)',  kcal:174, p:7.5, c:37, f:0.8 },
    { name:'Egg noodles, cooked',         cat:'Carbs & Grains', qty:1, unit:'cup (160g)',  kcal:221, p:7.3, c:40, f:3.3 },
    { name:'Rice noodles, cooked',        cat:'Carbs & Grains', qty:1, unit:'cup (176g)',  kcal:192, p:1.8, c:44, f:0.4 },
    { name:'Soba noodles, cooked',        cat:'Carbs & Grains', qty:1, unit:'cup (113g)',  kcal:113, p:5.8, c:24, f:0.1 },
    { name:'Udon noodles, cooked',        cat:'Carbs & Grains', qty:1, unit:'cup (213g)',  kcal:212, p:7,   c:43, f:0.6 },
    { name:'Ramen noodles (instant, dry)',cat:'Carbs & Grains', qty:1, unit:'packet (85g)',kcal:380, p:9,   c:54, f:14  },
    { name:'Glass noodles, cooked',       cat:'Carbs & Grains', qty:1, unit:'cup (190g)',  kcal:160, p:0.1, c:39, f:0.1 },
    { name:'Macaroni, cooked',            cat:'Carbs & Grains', qty:1, unit:'cup (140g)',  kcal:221, p:8,   c:43, f:1.3 },

    /* ─── Carbs & Grains — Bread & Bakery ──────────────────────────── */
    { name:'Whole wheat bread',    cat:'Carbs & Grains', qty:1,  unit:'slice (43g)',       kcal:110, p:5,   c:20, f:1.5 },
    { name:'White bread',          cat:'Carbs & Grains', qty:1,  unit:'slice (29g)',       kcal:77,  p:2,   c:15, f:1   },
    { name:'Sourdough bread',      cat:'Carbs & Grains', qty:1,  unit:'slice (50g)',       kcal:120, p:4,   c:24, f:1   },
    { name:'Rye bread',            cat:'Carbs & Grains', qty:1,  unit:'slice (32g)',       kcal:83,  p:2.7, c:15, f:1.1 },
    { name:'Ezekiel bread',        cat:'Carbs & Grains', qty:1,  unit:'slice (34g)',       kcal:80,  p:4,   c:15, f:0.5 },
    { name:'Gluten-free bread',    cat:'Carbs & Grains', qty:1,  unit:'slice (35g)',       kcal:100, p:2,   c:21, f:1.5 },
    { name:'Bagel, plain',         cat:'Carbs & Grains', qty:1,  unit:'medium (105g)',     kcal:277, p:11,  c:55, f:1.7 },
    { name:'English muffin',       cat:'Carbs & Grains', qty:1,  unit:'muffin (57g)',      kcal:134, p:5,   c:27, f:1.1 },
    { name:'Pita bread',           cat:'Carbs & Grains', qty:1,  unit:'large (60g)',       kcal:165, p:5.5, c:33, f:0.7 },
    { name:'Naan bread',           cat:'Carbs & Grains', qty:1,  unit:'piece (90g)',       kcal:262, p:9,   c:45, f:5   },
    { name:'Whole wheat tortilla', cat:'Carbs & Grains', qty:1,  unit:'large (49g)',       kcal:140, p:4,   c:24, f:4   },
    { name:'Corn tortilla',        cat:'Carbs & Grains', qty:1,  unit:'small (26g)',       kcal:52,  p:1.4, c:11, f:0.7 },
    { name:'Flour tortilla (10")', cat:'Carbs & Grains', qty:1,  unit:'tortilla (72g)',    kcal:218, p:5.8, c:36, f:6   },
    { name:'Croissant',            cat:'Carbs & Grains', qty:1,  unit:'medium (57g)',      kcal:231, p:5,   c:26, f:12  },
    { name:'Baguette slice',       cat:'Carbs & Grains', qty:1,  unit:'2 oz piece (57g)',  kcal:147, p:5,   c:29, f:1   },
    { name:'Ciabatta',             cat:'Carbs & Grains', qty:1,  unit:'slice (47g)',       kcal:120, p:4,   c:24, f:0.8 },
    { name:'Brioche bun',          cat:'Carbs & Grains', qty:1,  unit:'bun (57g)',         kcal:200, p:6,   c:28, f:8   },
    { name:'Hamburger bun',        cat:'Carbs & Grains', qty:1,  unit:'bun (44g)',         kcal:120, p:4,   c:22, f:2   },
    { name:'Dinner roll',          cat:'Carbs & Grains', qty:1,  unit:'roll (28g)',        kcal:87,  p:2.7, c:14, f:2.1 },
    { name:'Rice cake, plain',     cat:'Carbs & Grains', qty:1,  unit:'cake (9g)',         kcal:35,  p:1,   c:7,  f:0.3 },
    { name:'Soft pretzel',         cat:'Carbs & Grains', qty:1,  unit:'large (115g)',      kcal:340, p:9,   c:72, f:2.5 },

    /* ─── Carbs & Grains — Cereals ──────────────────────────────────── */
    { name:'Corn Flakes',              cat:'Carbs & Grains', qty:1,   unit:'cup (28g)',       kcal:100, p:2,   c:24, f:0.1 },
    { name:'Honey Nut Cheerios',       cat:'Carbs & Grains', qty:0.75,unit:'cup (28g)',       kcal:107, p:2,   c:22, f:1.5 },
    { name:'Cheerios (plain)',         cat:'Carbs & Grains', qty:1,   unit:'cup (28g)',       kcal:100, p:3,   c:20, f:2   },
    { name:'Special K',               cat:'Carbs & Grains', qty:1,   unit:'cup (31g)',       kcal:117, p:7,   c:22, f:0.5 },
    { name:'Raisin Bran',             cat:'Carbs & Grains', qty:1,   unit:'cup (59g)',       kcal:188, p:5,   c:46, f:1.5 },
    { name:'Frosted Mini Wheats',     cat:'Carbs & Grains', qty:1,   unit:'cup (59g)',       kcal:210, p:6,   c:49, f:1   },
    { name:'Shredded Wheat (plain)',  cat:'Carbs & Grains', qty:2,   unit:'biscuits (47g)',  kcal:162, p:5.5, c:37, f:0.7 },
    { name:'Granola, honey oat',      cat:'Carbs & Grains', qty:0.5, unit:'cup (57g)',       kcal:260, p:5,   c:44, f:8   },
    { name:'Muesli, unsweetened',     cat:'Carbs & Grains', qty:0.5, unit:'cup (55g)',       kcal:200, p:5,   c:38, f:3.5 },
    { name:'Bran flakes',             cat:'Carbs & Grains', qty:1,   unit:'cup (30g)',       kcal:100, p:3,   c:24, f:0.7 },
    { name:'Fiber One Original',      cat:'Carbs & Grains', qty:0.5, unit:'cup (30g)',       kcal:60,  p:2,   c:25, f:1   },

    /* ─── Carbs & Grains — Potatoes & Other ────────────────────────── */
    { name:'Sweet potato, baked',     cat:'Carbs & Grains', qty:1,  unit:'medium (150g)', kcal:130, p:3,   c:30, f:0.1 },
    { name:'White potato, baked',     cat:'Carbs & Grains', qty:1,  unit:'medium (173g)', kcal:161, p:4,   c:37, f:0.2 },
    { name:'Mashed potato (plain)',   cat:'Carbs & Grains', qty:1,  unit:'cup (210g)',    kcal:237, p:4,   c:35, f:9   },
    { name:'French fries, oven-baked',cat:'Carbs & Grains', qty:1,  unit:'cup (82g)',     kcal:196, p:2.5, c:32, f:7   },
    { name:'Tater tots, baked',       cat:'Carbs & Grains', qty:10, unit:'pieces (84g)',  kcal:160, p:2,   c:23, f:6   },
    { name:'Hash browns, cooked',     cat:'Carbs & Grains', qty:1,  unit:'cup (142g)',    kcal:270, p:3,   c:32, f:15  },
    { name:'French toast',            cat:'Carbs & Grains', qty:1,  unit:'slice (65g)',   kcal:149, p:5,   c:16, f:7   },
    { name:'Pancake (plain, 4")',     cat:'Carbs & Grains', qty:1,  unit:'pancake (38g)', kcal:86,  p:2.3, c:15, f:2   },
    { name:'Waffle (plain)',          cat:'Carbs & Grains', qty:1,  unit:'waffle (75g)',  kcal:218, p:5.9, c:25, f:11  },

    /* ─── Vegetables ────────────────────────────────────────────────── */
    { name:'Broccoli, steamed',         cat:'Vegetables', qty:1,   unit:'cup (156g)',    kcal:55,  p:4,   c:11,  f:0.6 },
    { name:'Broccoli, raw',             cat:'Vegetables', qty:1,   unit:'cup (91g)',     kcal:31,  p:2.6, c:6,   f:0.3 },
    { name:'Spinach, raw',              cat:'Vegetables', qty:1,   unit:'cup (30g)',     kcal:7,   p:1,   c:1,   f:0.1 },
    { name:'Spinach, cooked',           cat:'Vegetables', qty:1,   unit:'cup (180g)',    kcal:41,  p:5.3, c:6.8, f:0.5 },
    { name:'Kale, raw',                 cat:'Vegetables', qty:1,   unit:'cup (67g)',     kcal:33,  p:2.9, c:6,   f:0.6 },
    { name:'Kale, cooked',              cat:'Vegetables', qty:1,   unit:'cup (130g)',    kcal:36,  p:2.5, c:7.3, f:0.5 },
    { name:'Arugula, raw',              cat:'Vegetables', qty:1,   unit:'cup (20g)',     kcal:5,   p:0.5, c:0.7, f:0.1 },
    { name:'Romaine lettuce',           cat:'Vegetables', qty:2,   unit:'cups (94g)',    kcal:16,  p:1.5, c:2.7, f:0.3 },
    { name:'Mixed salad greens',        cat:'Vegetables', qty:2,   unit:'cups (60g)',    kcal:15,  p:1,   c:3,   f:0.2 },
    { name:'Asparagus, cooked',         cat:'Vegetables', qty:1,   unit:'cup (180g)',    kcal:40,  p:4,   c:7,   f:0.4 },
    { name:'Green beans, cooked',       cat:'Vegetables', qty:1,   unit:'cup (125g)',    kcal:44,  p:2,   c:10,  f:0.4 },
    { name:'Bell pepper, raw',          cat:'Vegetables', qty:1,   unit:'medium (119g)', kcal:31,  p:1,   c:7,   f:0.3 },
    { name:'Bell pepper, cooked',       cat:'Vegetables', qty:1,   unit:'cup (149g)',    kcal:38,  p:1.3, c:9,   f:0.3 },
    { name:'Tomato',                    cat:'Vegetables', qty:1,   unit:'medium (123g)', kcal:22,  p:1,   c:5,   f:0.2 },
    { name:'Cherry tomatoes',           cat:'Vegetables', qty:1,   unit:'cup (149g)',    kcal:27,  p:1.3, c:5.8, f:0.3 },
    { name:'Carrots, raw',              cat:'Vegetables', qty:1,   unit:'cup (128g)',    kcal:52,  p:1,   c:12,  f:0.3 },
    { name:'Carrot, 1 medium',          cat:'Vegetables', qty:1,   unit:'medium (61g)',  kcal:25,  p:0.6, c:6,   f:0.1 },
    { name:'Cucumber, sliced',          cat:'Vegetables', qty:1,   unit:'cup (119g)',    kcal:16,  p:0.7, c:3.8, f:0.1 },
    { name:'Zucchini, cooked',          cat:'Vegetables', qty:1,   unit:'cup (180g)',    kcal:29,  p:2,   c:7,   f:0.5 },
    { name:'Cauliflower, steamed',      cat:'Vegetables', qty:1,   unit:'cup (124g)',    kcal:29,  p:2,   c:5,   f:0.3 },
    { name:'Celery, raw',               cat:'Vegetables', qty:1,   unit:'cup (101g)',    kcal:16,  p:0.7, c:3,   f:0.2 },
    { name:'Onion, raw',                cat:'Vegetables', qty:1,   unit:'medium (110g)', kcal:44,  p:1.2, c:10,  f:0.1 },
    { name:'Garlic, raw',               cat:'Vegetables', qty:3,   unit:'cloves (9g)',   kcal:13,  p:0.6, c:3,   f:0   },
    { name:'Mushrooms, cooked',         cat:'Vegetables', qty:1,   unit:'cup (156g)',    kcal:44,  p:3,   c:8,   f:0.7 },
    { name:'Mushrooms, raw',            cat:'Vegetables', qty:1,   unit:'cup (70g)',     kcal:15,  p:2.2, c:2.3, f:0.2 },
    { name:'Brussels sprouts, roasted', cat:'Vegetables', qty:1,   unit:'cup (155g)',    kcal:56,  p:4,   c:11,  f:0.8 },
    { name:'Beets, cooked',             cat:'Vegetables', qty:1,   unit:'cup (170g)',    kcal:75,  p:2.9, c:17,  f:0.3 },
    { name:'Corn, cooked',              cat:'Vegetables', qty:1,   unit:'cup (154g)',    kcal:132, p:5,   c:29,  f:1.8 },
    { name:'Corn on the cob',           cat:'Vegetables', qty:1,   unit:'ear (148g)',    kcal:127, p:4.2, c:28,  f:1.8 },
    { name:'Peas, cooked',              cat:'Vegetables', qty:1,   unit:'cup (160g)',    kcal:134, p:8.6, c:25,  f:0.4 },
    { name:'Snap peas, raw',            cat:'Vegetables', qty:1,   unit:'cup (63g)',     kcal:27,  p:1.8, c:5,   f:0.1 },
    { name:'Butternut squash, cooked',  cat:'Vegetables', qty:1,   unit:'cup (205g)',    kcal:82,  p:1.8, c:22,  f:0.1 },
    { name:'Spaghetti squash, cooked',  cat:'Vegetables', qty:1,   unit:'cup (155g)',    kcal:42,  p:1,   c:10,  f:0.4 },
    { name:'Bok choy, raw',             cat:'Vegetables', qty:1,   unit:'cup (70g)',     kcal:9,   p:1,   c:1.5, f:0.1 },
    { name:'Bok choy, cooked',          cat:'Vegetables', qty:1,   unit:'cup (170g)',    kcal:20,  p:2.7, c:3,   f:0.3 },
    { name:'Cabbage, cooked',           cat:'Vegetables', qty:1,   unit:'cup (150g)',    kcal:34,  p:2,   c:8.2, f:0.1 },
    { name:'Eggplant, cooked',          cat:'Vegetables', qty:1,   unit:'cup (99g)',     kcal:35,  p:0.8, c:8.7, f:0.2 },
    { name:'Swiss chard, cooked',       cat:'Vegetables', qty:1,   unit:'cup (175g)',    kcal:35,  p:3.3, c:7,   f:0.1 },
    { name:'Collard greens, cooked',    cat:'Vegetables', qty:1,   unit:'cup (190g)',    kcal:49,  p:4,   c:9,   f:0.7 },
    { name:'Edamame, shelled',          cat:'Vegetables', qty:1,   unit:'cup (155g)',    kcal:188, p:18,  c:14,  f:8   },
    { name:'Okra, cooked',              cat:'Vegetables', qty:1,   unit:'cup (160g)',    kcal:36,  p:3,   c:7.2, f:0.3 },
    { name:'Artichoke hearts, cooked',  cat:'Vegetables', qty:0.5, unit:'cup (84g)',     kcal:45,  p:2.4, c:10,  f:0.2 },
    { name:'Jicama, raw',               cat:'Vegetables', qty:1,   unit:'cup (130g)',    kcal:46,  p:0.9, c:11,  f:0.1 },
    { name:'Leek, cooked',              cat:'Vegetables', qty:0.5, unit:'cup (52g)',     kcal:27,  p:0.7, c:6.7, f:0.2 },
    { name:'Parsnip, cooked',           cat:'Vegetables', qty:0.5, unit:'cup (78g)',     kcal:55,  p:1,   c:13,  f:0.2 },
    { name:'Radishes, raw',             cat:'Vegetables', qty:1,   unit:'cup (116g)',    kcal:19,  p:0.8, c:3.9, f:0.1 },
    { name:'Bean sprouts, raw',         cat:'Vegetables', qty:1,   unit:'cup (104g)',    kcal:31,  p:3.2, c:6,   f:0.2 },
    { name:'Water chestnuts',           cat:'Vegetables', qty:0.5, unit:'cup (70g)',     kcal:35,  p:0.7, c:8.7, f:0   },
    { name:'Bamboo shoots, canned',     cat:'Vegetables', qty:0.5, unit:'cup (65g)',     kcal:13,  p:1.1, c:2.3, f:0.2 },
    { name:'Olives, green',             cat:'Vegetables', qty:5,   unit:'olives (21g)',  kcal:25,  p:0.2, c:1.3, f:2.3 },
    { name:'Olives, black',             cat:'Vegetables', qty:5,   unit:'olives (21g)',  kcal:25,  p:0.2, c:1.3, f:2.3 },
    { name:'Pickles, dill',             cat:'Vegetables', qty:1,   unit:'medium (65g)',  kcal:11,  p:0.4, c:2.6, f:0.1 },
    { name:'Sauerkraut',                cat:'Vegetables', qty:0.5, unit:'cup (75g)',     kcal:13,  p:0.6, c:2.9, f:0   },
    { name:'Kimchi',                    cat:'Vegetables', qty:0.5, unit:'cup (75g)',     kcal:22,  p:1.5, c:3.4, f:0.5 },
    { name:'Jalapeño, raw',             cat:'Vegetables', qty:1,   unit:'pepper (14g)',  kcal:4,   p:0.1, c:0.9, f:0.1 },
    { name:'Sun-dried tomatoes',        cat:'Vegetables', qty:0.25,unit:'cup (27g)',     kcal:59,  p:1.6, c:6.5, f:3.5 },
    { name:'Capers',                    cat:'Vegetables', qty:1,   unit:'tbsp (9g)',     kcal:2,   p:0.2, c:0.4, f:0.1 },
    { name:'Roasted red peppers',       cat:'Vegetables', qty:0.25,unit:'cup (37g)',     kcal:15,  p:0.5, c:3.6, f:0.1 },
    { name:'Fennel, raw',               cat:'Vegetables', qty:1,   unit:'cup (87g)',     kcal:27,  p:1.1, c:6.3, f:0.2 },
    { name:'Broccolini',                cat:'Vegetables', qty:1,   unit:'cup (75g)',     kcal:25,  p:2,   c:3.7, f:0.3 },
    { name:'Seaweed (nori)',             cat:'Vegetables', qty:1,   unit:'sheet (3g)',    kcal:10,  p:0.9, c:1.2, f:0.2 },
    { name:'Watercress, raw',           cat:'Vegetables', qty:1,   unit:'cup (34g)',     kcal:4,   p:0.8, c:0.4, f:0   },
    { name:'Rutabaga, cooked',          cat:'Vegetables', qty:1,   unit:'cup (170g)',    kcal:66,  p:2.2, c:15,  f:0.4 },
    { name:'Turnip, cooked',            cat:'Vegetables', qty:1,   unit:'cup (156g)',    kcal:34,  p:1.1, c:7.9, f:0.1 },

    /* ─── Fruit ─────────────────────────────────────────────────────── */
    { name:'Banana',               cat:'Fruit', qty:1,   unit:'medium (118g)',  kcal:105, p:1,   c:27,  f:0.4 },
    { name:'Apple',                cat:'Fruit', qty:1,   unit:'medium (182g)',  kcal:95,  p:0.5, c:25,  f:0.3 },
    { name:'Orange',               cat:'Fruit', qty:1,   unit:'medium (131g)',  kcal:62,  p:1,   c:15,  f:0.2 },
    { name:'Clementine',           cat:'Fruit', qty:1,   unit:'small (74g)',    kcal:35,  p:0.6, c:9,   f:0.1 },
    { name:'Grapefruit',           cat:'Fruit', qty:0.5, unit:'medium (123g)',  kcal:41,  p:0.8, c:10,  f:0.1 },
    { name:'Blueberries',          cat:'Fruit', qty:1,   unit:'cup (148g)',     kcal:84,  p:1,   c:21,  f:0.5 },
    { name:'Strawberries',         cat:'Fruit', qty:1,   unit:'cup (152g)',     kcal:49,  p:1,   c:12,  f:0.5 },
    { name:'Raspberries',          cat:'Fruit', qty:1,   unit:'cup (123g)',     kcal:64,  p:1.5, c:15,  f:0.8 },
    { name:'Blackberries',         cat:'Fruit', qty:1,   unit:'cup (144g)',     kcal:62,  p:2,   c:14,  f:0.7 },
    { name:'Grapes',               cat:'Fruit', qty:1,   unit:'cup (151g)',     kcal:104, p:1,   c:27,  f:0.2 },
    { name:'Watermelon, cubed',    cat:'Fruit', qty:2,   unit:'cups (280g)',    kcal:86,  p:1.7, c:22,  f:0.4 },
    { name:'Cantaloupe, cubed',    cat:'Fruit', qty:1,   unit:'cup (160g)',     kcal:54,  p:1.3, c:13,  f:0.3 },
    { name:'Pineapple, chunks',    cat:'Fruit', qty:1,   unit:'cup (165g)',     kcal:82,  p:1,   c:22,  f:0.2 },
    { name:'Mango, sliced',        cat:'Fruit', qty:1,   unit:'cup (165g)',     kcal:99,  p:1,   c:25,  f:0.6 },
    { name:'Peach',                cat:'Fruit', qty:1,   unit:'medium (150g)',  kcal:59,  p:1.4, c:14,  f:0.4 },
    { name:'Nectarine',            cat:'Fruit', qty:1,   unit:'medium (142g)',  kcal:62,  p:1.5, c:15,  f:0.5 },
    { name:'Plum',                 cat:'Fruit', qty:1,   unit:'medium (66g)',   kcal:30,  p:0.5, c:8,   f:0.2 },
    { name:'Pear',                 cat:'Fruit', qty:1,   unit:'medium (178g)',  kcal:101, p:0.6, c:27,  f:0.2 },
    { name:'Kiwi',                 cat:'Fruit', qty:1,   unit:'medium (76g)',   kcal:42,  p:0.8, c:10,  f:0.4 },
    { name:'Cherries',             cat:'Fruit', qty:1,   unit:'cup (154g)',     kcal:97,  p:1.6, c:25,  f:0.3 },
    { name:'Papaya, cubed',        cat:'Fruit', qty:1,   unit:'cup (145g)',     kcal:55,  p:0.9, c:14,  f:0.2 },
    { name:'Avocado, half',        cat:'Fruit', qty:0.5, unit:'medium (100g)', kcal:160, p:2,   c:9,   f:15  },
    { name:'Avocado, whole',       cat:'Fruit', qty:1,   unit:'medium (200g)', kcal:320, p:4,   c:18,  f:30  },
    { name:'Dates, pitted',        cat:'Fruit', qty:2,   unit:'dates (48g)',   kcal:133, p:1,   c:36,  f:0.1 },
    { name:'Raisins',              cat:'Fruit', qty:0.25,unit:'cup (41g)',     kcal:130, p:1.4, c:34,  f:0.2 },
    { name:'Pomegranate seeds',    cat:'Fruit', qty:0.5, unit:'cup (87g)',     kcal:72,  p:1.5, c:16,  f:1   },
    { name:'Lychee',               cat:'Fruit', qty:10,  unit:'pieces (100g)', kcal:66,  p:0.8, c:17,  f:0.4 },
    { name:'Persimmon',            cat:'Fruit', qty:1,   unit:'medium (168g)', kcal:118, p:1,   c:31,  f:0.3 },
    { name:'Guava',                cat:'Fruit', qty:1,   unit:'medium (55g)',  kcal:37,  p:1.4, c:8,   f:0.5 },
    { name:'Coconut meat, fresh',  cat:'Fruit', qty:1,   unit:'oz (28g)',      kcal:99,  p:1,   c:4.3, f:9.5 },
    { name:'Frozen mixed berries', cat:'Fruit', qty:1,   unit:'cup (140g)',    kcal:70,  p:0.5, c:17,  f:0.5 },
    { name:'Lime',                 cat:'Fruit', qty:1,   unit:'medium (67g)',  kcal:20,  p:0.5, c:7,   f:0.1 },
    { name:'Lemon',                cat:'Fruit', qty:1,   unit:'medium (58g)',  kcal:17,  p:0.6, c:5.4, f:0.2 },

    /* ─── Dairy & Eggs ──────────────────────────────────────────────── */
    { name:'Greek yogurt, nonfat',       cat:'Dairy & Eggs', qty:1,   unit:'cup (245g)',   kcal:130, p:23,   c:9,   f:0.5 },
    { name:'Greek yogurt, 2%',           cat:'Dairy & Eggs', qty:1,   unit:'cup (245g)',   kcal:173, p:24,   c:10,  f:4.5 },
    { name:'Greek yogurt, whole milk',   cat:'Dairy & Eggs', qty:1,   unit:'cup (245g)',   kcal:190, p:20,   c:8,   f:10  },
    { name:'Skyr (Icelandic yogurt)',    cat:'Dairy & Eggs', qty:1,   unit:'cup (227g)',   kcal:100, p:17,   c:7,   f:0   },
    { name:'Regular yogurt, low-fat',   cat:'Dairy & Eggs', qty:1,   unit:'cup (245g)',   kcal:143, p:12,   c:16,  f:3.5 },
    { name:'Cottage cheese, low-fat',   cat:'Dairy & Eggs', qty:0.5, unit:'cup (113g)',   kcal:90,  p:12,   c:5,   f:2.5 },
    { name:'Cottage cheese, full-fat',  cat:'Dairy & Eggs', qty:0.5, unit:'cup (113g)',   kcal:111, p:12.5, c:3,   f:5   },
    { name:'Skim milk',                 cat:'Dairy & Eggs', qty:1,   unit:'cup (245g)',   kcal:83,  p:8,    c:12,  f:0.2 },
    { name:'2% milk',                   cat:'Dairy & Eggs', qty:1,   unit:'cup (244g)',   kcal:122, p:8,    c:12,  f:4.8 },
    { name:'Whole milk',                cat:'Dairy & Eggs', qty:1,   unit:'cup (244g)',   kcal:149, p:8,    c:12,  f:8   },
    { name:'Chocolate milk (2%)',       cat:'Dairy & Eggs', qty:1,   unit:'cup (244g)',   kcal:190, p:8,    c:30,  f:5   },
    { name:'Almond milk, unsweetened',  cat:'Dairy & Eggs', qty:1,   unit:'cup (240g)',   kcal:30,  p:1,    c:1,   f:2.5 },
    { name:'Oat milk',                  cat:'Dairy & Eggs', qty:1,   unit:'cup (240g)',   kcal:120, p:3,    c:16,  f:5   },
    { name:'Soy milk, unsweetened',     cat:'Dairy & Eggs', qty:1,   unit:'cup (240g)',   kcal:80,  p:7,    c:4,   f:4   },
    { name:'Coconut milk, canned',      cat:'Dairy & Eggs', qty:0.25,unit:'cup (60g)',    kcal:110, p:1,    c:3,   f:11  },
    { name:'Cheddar cheese',            cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:113, p:7,    c:0.4, f:9   },
    { name:'Mozzarella, part-skim',     cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:72,  p:7,    c:1,   f:4.5 },
    { name:'String cheese',             cat:'Dairy & Eggs', qty:1,   unit:'stick (28g)',  kcal:80,  p:7,    c:1,   f:6   },
    { name:'Swiss cheese',              cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:108, p:8,    c:0.4, f:8   },
    { name:'Parmesan, grated',          cat:'Dairy & Eggs', qty:1,   unit:'tbsp (5g)',    kcal:22,  p:1.9,  c:0.2, f:1.4 },
    { name:'Feta cheese',               cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:75,  p:4,    c:1.2, f:6   },
    { name:'Goat cheese (chèvre)',      cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:76,  p:5,    c:0.3, f:6   },
    { name:'Gouda',                     cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:101, p:7,    c:0.6, f:8   },
    { name:'Provolone',                 cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:98,  p:7,    c:0.6, f:7.5 },
    { name:'Brie',                      cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:94,  p:6,    c:0.1, f:7.8 },
    { name:'Blue cheese',               cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:100, p:6,    c:0.7, f:8   },
    { name:'Pepper jack',               cat:'Dairy & Eggs', qty:1,   unit:'oz (28g)',     kcal:110, p:6.5,  c:0.5, f:9   },
    { name:'American cheese, processed',cat:'Dairy & Eggs', qty:1,   unit:'slice (21g)',  kcal:60,  p:3.5,  c:1,   f:4.5 },
    { name:'Cream cheese',              cat:'Dairy & Eggs', qty:1,   unit:'tbsp (14g)',   kcal:50,  p:0.9,  c:0.7, f:5   },
    { name:'Ricotta, part-skim',        cat:'Dairy & Eggs', qty:0.5, unit:'cup (124g)',   kcal:171, p:14,   c:6.4, f:10  },
    { name:'Mascarpone',                cat:'Dairy & Eggs', qty:1,   unit:'tbsp (15g)',   kcal:60,  p:1,    c:0.5, f:6   },
    { name:'Sour cream',                cat:'Dairy & Eggs', qty:2,   unit:'tbsp (28g)',   kcal:61,  p:0.9,  c:1.3, f:6   },
    { name:'Heavy cream',               cat:'Dairy & Eggs', qty:1,   unit:'tbsp (15g)',   kcal:51,  p:0.4,  c:0.4, f:5.5 },
    { name:'Half and half',             cat:'Dairy & Eggs', qty:2,   unit:'tbsp (30g)',   kcal:39,  p:1,    c:1.3, f:3.5 },
    { name:'Kefir (plain)',             cat:'Dairy & Eggs', qty:1,   unit:'cup (243g)',   kcal:110, p:10,   c:12,  f:2   },
    { name:'Butter',                    cat:'Dairy & Eggs', qty:1,   unit:'tbsp (14g)',   kcal:102, p:0.1,  c:0,   f:12  },

    /* ─── Fats & Nuts ───────────────────────────────────────────────── */
    { name:'Olive oil',        cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:119, p:0,   c:0,   f:14   },
    { name:'Avocado oil',      cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:124, p:0,   c:0,   f:14   },
    { name:'Coconut oil',      cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:121, p:0,   c:0,   f:14   },
    { name:'Canola oil',       cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:124, p:0,   c:0,   f:14   },
    { name:'Vegetable oil',    cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:120, p:0,   c:0,   f:14   },
    { name:'Sesame oil',       cat:'Fats & Nuts', qty:1, unit:'tsp (5g)',   kcal:40,  p:0,   c:0,   f:4.5  },
    { name:'Walnut oil',       cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:120, p:0,   c:0,   f:14   },
    { name:'Flaxseed oil',     cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:120, p:0,   c:0,   f:14   },
    { name:'Ghee',             cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:112, p:0,   c:0,   f:13   },
    { name:'MCT oil',          cat:'Fats & Nuts', qty:1, unit:'tbsp (14g)', kcal:130, p:0,   c:0,   f:14   },
    { name:'Lard',             cat:'Fats & Nuts', qty:1, unit:'tbsp (13g)', kcal:115, p:0,   c:0,   f:13   },
    { name:'Peanut butter',    cat:'Fats & Nuts', qty:2, unit:'tbsp (32g)', kcal:188, p:8,   c:6,   f:16   },
    { name:'Almond butter',    cat:'Fats & Nuts', qty:2, unit:'tbsp (32g)', kcal:196, p:7,   c:6,   f:18   },
    { name:'Cashew butter',    cat:'Fats & Nuts', qty:2, unit:'tbsp (32g)', kcal:188, p:6,   c:9,   f:16   },
    { name:'Sunflower butter', cat:'Fats & Nuts', qty:2, unit:'tbsp (32g)', kcal:186, p:6.4, c:8.8, f:16   },
    { name:'Tahini',           cat:'Fats & Nuts', qty:1, unit:'tbsp (15g)', kcal:89,  p:2.7, c:3.2, f:8    },
    { name:'Almonds',          cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:164, p:6,   c:6,   f:14   },
    { name:'Walnuts',          cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:185, p:4,   c:4,   f:18   },
    { name:'Cashews',          cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:157, p:5,   c:9,   f:12   },
    { name:'Pistachios',       cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:160, p:6,   c:8,   f:13   },
    { name:'Pecans',           cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:196, p:3,   c:4,   f:20   },
    { name:'Macadamia nuts',   cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:204, p:2,   c:4,   f:21   },
    { name:'Brazil nuts',      cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:187, p:4,   c:3.4, f:19   },
    { name:'Hazelnuts',        cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:178, p:4.2, c:4.7, f:17   },
    { name:'Mixed nuts',       cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:173, p:5,   c:6,   f:16   },
    { name:'Chia seeds',       cat:'Fats & Nuts', qty:1, unit:'tbsp (12g)', kcal:58,  p:2,   c:5,   f:4    },
    { name:'Ground flaxseed',  cat:'Fats & Nuts', qty:1, unit:'tbsp (7g)',  kcal:37,  p:1,   c:2,   f:3    },
    { name:'Hemp seeds',       cat:'Fats & Nuts', qty:3, unit:'tbsp (30g)', kcal:166, p:9.5, c:2.6, f:14.6 },
    { name:'Pumpkin seeds',    cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:163, p:8.5, c:4.2, f:14   },
    { name:'Sunflower seeds',  cat:'Fats & Nuts', qty:1, unit:'oz (28g)',   kcal:163, p:5.5, c:6.8, f:14   },
    { name:'Sesame seeds',     cat:'Fats & Nuts', qty:1, unit:'tbsp (9g)',  kcal:52,  p:1.6, c:2.1, f:4.5  },

    /* ─── Legumes ───────────────────────────────────────────────────── */
    { name:'Black beans, cooked',      cat:'Legumes', qty:1,   unit:'cup (172g)', kcal:227, p:15,  c:41, f:0.9 },
    { name:'Chickpeas, cooked',        cat:'Legumes', qty:1,   unit:'cup (164g)', kcal:269, p:15,  c:45, f:4   },
    { name:'Lentils, cooked',          cat:'Legumes', qty:1,   unit:'cup (198g)', kcal:230, p:18,  c:40, f:0.8 },
    { name:'Red lentils, cooked',      cat:'Legumes', qty:1,   unit:'cup (198g)', kcal:230, p:18,  c:40, f:0.6 },
    { name:'Kidney beans, cooked',     cat:'Legumes', qty:1,   unit:'cup (177g)', kcal:225, p:15,  c:40, f:0.9 },
    { name:'Pinto beans, cooked',      cat:'Legumes', qty:1,   unit:'cup (171g)', kcal:245, p:15,  c:45, f:1.1 },
    { name:'White beans, cooked',      cat:'Legumes', qty:1,   unit:'cup (179g)', kcal:249, p:17,  c:45, f:0.6 },
    { name:'Navy beans, cooked',       cat:'Legumes', qty:1,   unit:'cup (182g)', kcal:255, p:15,  c:47, f:1.1 },
    { name:'Cannellini beans, cooked', cat:'Legumes', qty:1,   unit:'cup (179g)', kcal:249, p:17,  c:45, f:0.6 },
    { name:'Mung beans, cooked',       cat:'Legumes', qty:1,   unit:'cup (202g)', kcal:212, p:14,  c:39, f:0.8 },
    { name:'Fava beans, cooked',       cat:'Legumes', qty:1,   unit:'cup (170g)', kcal:187, p:13,  c:33, f:0.7 },
    { name:'Edamame, shelled',         cat:'Legumes', qty:1,   unit:'cup (155g)', kcal:188, p:18,  c:14, f:8   },
    { name:'Refried beans, canned',    cat:'Legumes', qty:0.5, unit:'cup (123g)', kcal:135, p:8,   c:25, f:1.5 },
    { name:'Tofu, firm',               cat:'Legumes', qty:100, unit:'g',          kcal:144, p:17,  c:3,  f:9   },
    { name:'Tofu, silken',             cat:'Legumes', qty:100, unit:'g',          kcal:55,  p:5.3, c:2.4,f:2.7 },
    { name:'Tempeh',                   cat:'Legumes', qty:100, unit:'g',          kcal:192, p:20,  c:8,  f:11  },
    { name:'Hummus',                   cat:'Legumes', qty:2,   unit:'tbsp (30g)', kcal:70,  p:2,   c:6,  f:5   },
    { name:'Split peas, cooked',       cat:'Legumes', qty:1,   unit:'cup (196g)', kcal:231, p:16,  c:41, f:0.8 },
    { name:'Soybeans, roasted',        cat:'Legumes', qty:0.25,unit:'cup (43g)',  kcal:202, p:15,  c:14, f:11  },

    /* ─── Beverages ─────────────────────────────────────────────────── */
    { name:'Coffee, black',             cat:'Beverages', qty:1, unit:'cup (240ml)',    kcal:2,   p:0.3, c:0,   f:0   },
    { name:'Cold brew coffee',          cat:'Beverages', qty:1, unit:'cup (240ml)',    kcal:5,   p:0.5, c:0.5, f:0   },
    { name:'Espresso',                  cat:'Beverages', qty:1, unit:'shot (30ml)',    kcal:3,   p:0.3, c:0.5, f:0   },
    { name:'Latte, whole milk (12 oz)', cat:'Beverages', qty:1, unit:'drink (360ml)', kcal:190, p:10,  c:18,  f:7   },
    { name:'Cappuccino (whole milk)',   cat:'Beverages', qty:1, unit:'drink (360ml)', kcal:120, p:8,   c:10,  f:4   },
    { name:'Matcha latte (whole milk)', cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:150, p:7,   c:14,  f:6   },
    { name:'Black tea',                 cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:2,   p:0.1, c:0.7, f:0   },
    { name:'Green tea',                 cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:2,   p:0.5, c:0.5, f:0   },
    { name:'Yerba mate',                cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:5,   p:0.3, c:0.3, f:0   },
    { name:'Orange juice, fresh',       cat:'Beverages', qty:1, unit:'cup (248ml)',   kcal:112, p:1.7, c:26,  f:0.5 },
    { name:'Apple juice',               cat:'Beverages', qty:1, unit:'cup (248ml)',   kcal:114, p:0.2, c:28,  f:0.3 },
    { name:'Tomato juice',              cat:'Beverages', qty:1, unit:'cup (243ml)',   kcal:41,  p:1.9, c:10,  f:0.2 },
    { name:'Coconut water',             cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:46,  p:1.7, c:9,   f:0.5 },
    { name:'Bone broth, beef',          cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:40,  p:6,   c:3,   f:1   },
    { name:'Bone broth, chicken',       cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:35,  p:5,   c:2,   f:1   },
    { name:'Sparkling water',           cat:'Beverages', qty:1, unit:'can (355ml)',   kcal:0,   p:0,   c:0,   f:0   },
    { name:'Diet soda',                 cat:'Beverages', qty:1, unit:'can (355ml)',   kcal:0,   p:0,   c:0,   f:0   },
    { name:'Regular soda (Coke)',       cat:'Beverages', qty:1, unit:'can (355ml)',   kcal:140, p:0,   c:39,  f:0   },
    { name:'Energy drink (Red Bull)',   cat:'Beverages', qty:1, unit:'can (250ml)',   kcal:110, p:1,   c:27,  f:0   },
    { name:'Sports drink (Gatorade)',   cat:'Beverages', qty:1, unit:'bottle (591ml)',kcal:140, p:0,   c:36,  f:0   },
    { name:'Kombucha',                  cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:60,  p:0.5, c:14,  f:0   },
    { name:'Protein shake (homemade)',  cat:'Beverages', qty:1, unit:'shake (~400ml)',kcal:280, p:30,  c:25,  f:6   },
    { name:'V8 Vegetable Juice',        cat:'Beverages', qty:1, unit:'cup (240ml)',   kcal:50,  p:2,   c:10,  f:0   },
    { name:'Cranberry juice (unswtnd)', cat:'Beverages', qty:1, unit:'cup (248ml)',   kcal:116, p:1,   c:31,  f:0.3 },
    { name:'Pineapple juice',           cat:'Beverages', qty:1, unit:'cup (250ml)',   kcal:133, p:0.9, c:32,  f:0.2 },

    /* ─── Condiments ────────────────────────────────────────────────── */
    { name:'Ketchup',             cat:'Condiments', qty:1,   unit:'tbsp (17g)',  kcal:19,  p:0.3, c:5,   f:0   },
    { name:'Yellow mustard',      cat:'Condiments', qty:1,   unit:'tsp (5g)',    kcal:3,   p:0.2, c:0.3, f:0.2 },
    { name:'Dijon mustard',       cat:'Condiments', qty:1,   unit:'tsp (5g)',    kcal:5,   p:0.3, c:0.3, f:0.3 },
    { name:'Mayonnaise',          cat:'Condiments', qty:1,   unit:'tbsp (14g)',  kcal:94,  p:0.1, c:0.1, f:10  },
    { name:'Light mayonnaise',    cat:'Condiments', qty:1,   unit:'tbsp (15g)',  kcal:35,  p:0,   c:2,   f:3.5 },
    { name:'Ranch dressing',      cat:'Condiments', qty:2,   unit:'tbsp (30g)',  kcal:73,  p:0.4, c:1,   f:7.7 },
    { name:'Caesar dressing',     cat:'Condiments', qty:2,   unit:'tbsp (30g)',  kcal:78,  p:0.6, c:0.5, f:8   },
    { name:'Italian dressing',    cat:'Condiments', qty:2,   unit:'tbsp (30g)',  kcal:43,  p:0.1, c:1.9, f:3.9 },
    { name:'Balsamic vinegar',    cat:'Condiments', qty:1,   unit:'tbsp (16g)',  kcal:14,  p:0,   c:2.7, f:0   },
    { name:'Apple cider vinegar', cat:'Condiments', qty:1,   unit:'tbsp (15ml)', kcal:3,  p:0,   c:0.1, f:0   },
    { name:'Soy sauce',           cat:'Condiments', qty:1,   unit:'tbsp (18g)',  kcal:11,  p:1.9, c:1,   f:0   },
    { name:'Fish sauce',          cat:'Condiments', qty:1,   unit:'tbsp (18g)',  kcal:10,  p:1.4, c:1,   f:0   },
    { name:'Oyster sauce',        cat:'Condiments', qty:1,   unit:'tbsp (18g)',  kcal:29,  p:0.5, c:7.1, f:0   },
    { name:'Hoisin sauce',        cat:'Condiments', qty:1,   unit:'tbsp (16g)',  kcal:35,  p:0.5, c:7,   f:0.5 },
    { name:'Sriracha',            cat:'Condiments', qty:1,   unit:'tsp (5g)',    kcal:6,   p:0,   c:1.3, f:0   },
    { name:'Hot sauce (Tabasco)', cat:'Condiments', qty:1,   unit:'tsp (4g)',    kcal:1,   p:0,   c:0,   f:0   },
    { name:"Frank's RedHot",      cat:'Condiments', qty:1,   unit:'tsp (5g)',    kcal:0,   p:0,   c:0,   f:0   },
    { name:'BBQ sauce',           cat:'Condiments', qty:2,   unit:'tbsp (34g)',  kcal:56,  p:0.3, c:13,  f:0.2 },
    { name:'Teriyaki sauce',      cat:'Condiments', qty:2,   unit:'tbsp (30g)',  kcal:30,  p:1.4, c:6,   f:0.1 },
    { name:'Sweet chili sauce',   cat:'Condiments', qty:2,   unit:'tbsp (32g)',  kcal:80,  p:0.2, c:20,  f:0   },
    { name:'Worcestershire sauce',cat:'Condiments', qty:1,   unit:'tsp (6g)',    kcal:5,   p:0.1, c:1.2, f:0   },
    { name:'Miso paste (white)',  cat:'Condiments', qty:1,   unit:'tbsp (17g)',  kcal:34,  p:2,   c:4.3, f:1   },
    { name:'Miso paste (red)',    cat:'Condiments', qty:1,   unit:'tbsp (17g)',  kcal:34,  p:2.2, c:4,   f:1   },
    { name:'Gochujang',           cat:'Condiments', qty:1,   unit:'tbsp (17g)',  kcal:45,  p:1.5, c:10,  f:0.5 },
    { name:'Ponzu sauce',         cat:'Condiments', qty:1,   unit:'tbsp (16g)',  kcal:10,  p:0.5, c:2,   f:0   },
    { name:'Salsa',               cat:'Condiments', qty:2,   unit:'tbsp (32g)',  kcal:10,  p:0,   c:2,   f:0   },
    { name:'Guacamole',           cat:'Condiments', qty:2,   unit:'tbsp (30g)',  kcal:45,  p:0.5, c:2.3, f:4   },
    { name:'Pesto',               cat:'Condiments', qty:2,   unit:'tbsp (30g)',  kcal:145, p:3,   c:2,   f:14  },
    { name:'Marinara sauce',      cat:'Condiments', qty:0.5, unit:'cup (125g)',  kcal:70,  p:2,   c:13,  f:1.5 },
    { name:'Tzatziki',            cat:'Condiments', qty:2,   unit:'tbsp (28g)',  kcal:35,  p:2,   c:2,   f:2   },
    { name:'Chimichurri',         cat:'Condiments', qty:2,   unit:'tbsp (28g)',  kcal:60,  p:0.3, c:1.5, f:6   },
    { name:'Maple syrup',         cat:'Condiments', qty:1,   unit:'tbsp (20g)',  kcal:52,  p:0,   c:13,  f:0   },
    { name:'Honey',               cat:'Condiments', qty:1,   unit:'tbsp (21g)',  kcal:64,  p:0,   c:17,  f:0   },

    /* ─── Snacks ────────────────────────────────────────────────────── */
    { name:'Protein bar',               cat:'Snacks', qty:1,   unit:'bar (60g)',      kcal:220, p:20,  c:23,  f:7   },
    { name:'Beef jerky',                cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:80,  p:13,  c:5,   f:1   },
    { name:'Turkey jerky',              cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:70,  p:14,  c:3,   f:0.5 },
    { name:'Pork rinds (chicharrones)', cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:154, p:17,  c:0,   f:9   },
    { name:'Dark chocolate (70%)',      cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:170, p:2,   c:13,  f:12  },
    { name:'Dark chocolate (85%)',      cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:170, p:3,   c:8,   f:15  },
    { name:'Milk chocolate',            cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:153, p:2,   c:17,  f:9   },
    { name:'Popcorn, air-popped',       cat:'Snacks', qty:3,   unit:'cups (24g)',     kcal:93,  p:3,   c:19,  f:1   },
    { name:'Pretzels',                  cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:108, p:3,   c:23,  f:0.8 },
    { name:'Potato chips',              cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:152, p:2,   c:15,  f:10  },
    { name:'Tortilla chips',            cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:140, p:2,   c:19,  f:7   },
    { name:'Crackers, whole wheat',     cat:'Snacks', qty:1,   unit:'oz (28g)',       kcal:142, p:3,   c:20,  f:5   },
    { name:'Ritz crackers',             cat:'Snacks', qty:5,   unit:'crackers (16g)', kcal:79,  p:1,   c:10,  f:4   },
    { name:'Graham crackers',           cat:'Snacks', qty:2,   unit:'squares (28g)',  kcal:118, p:2,   c:22,  f:2.7 },
    { name:'Seaweed snacks',            cat:'Snacks', qty:1,   unit:'package (5g)',   kcal:25,  p:0.5, c:1.2, f:2   },
    { name:'Granola',                   cat:'Snacks', qty:0.5, unit:'cup (61g)',      kcal:280, p:7,   c:38,  f:12  },
    { name:'Trail mix',                 cat:'Snacks', qty:0.25,unit:'cup (35g)',      kcal:140, p:4,   c:15,  f:8   },
    { name:'Rice cakes',                cat:'Snacks', qty:1,   unit:'cake (9g)',      kcal:35,  p:1,   c:7,   f:0.3 },
    { name:'Gummy bears',               cat:'Snacks', qty:10,  unit:'bears (30g)',    kcal:107, p:2,   c:26,  f:0   },
    { name:'Fruit leather',             cat:'Snacks', qty:1,   unit:'roll (14g)',     kcal:50,  p:0,   c:12,  f:0   },

    /* ─── Fast Food ─────────────────────────────────────────────────── */
    { name:"McDonald's Big Mac",                   cat:'Fast Food', qty:1,   unit:'burger (213g)',    kcal:550, p:25, c:44, f:30  },
    { name:"McDonald's McDouble",                  cat:'Fast Food', qty:1,   unit:'burger (175g)',    kcal:450, p:25, c:35, f:20  },
    { name:"McDonald's Quarter Pounder w/ Cheese", cat:'Fast Food', qty:1,   unit:'burger (218g)',    kcal:520, p:30, c:43, f:26  },
    { name:"McDonald's McChicken",                 cat:'Fast Food', qty:1,   unit:'sandwich (147g)',  kcal:400, p:14, c:40, f:22  },
    { name:"McDonald's Egg McMuffin",              cat:'Fast Food', qty:1,   unit:'sandwich (135g)',  kcal:300, p:18, c:30, f:12  },
    { name:"McDonald's Fries (small)",             cat:'Fast Food', qty:1,   unit:'serving (71g)',    kcal:230, p:3,  c:29, f:11  },
    { name:"McDonald's Fries (medium)",            cat:'Fast Food', qty:1,   unit:'serving (117g)',   kcal:320, p:4,  c:44, f:15  },
    { name:"McDonald's Fries (large)",             cat:'Fast Food', qty:1,   unit:'serving (154g)',   kcal:490, p:6,  c:66, f:23  },
    { name:"Burger King Whopper",                  cat:'Fast Food', qty:1,   unit:'burger (270g)',    kcal:657, p:28, c:49, f:40  },
    { name:"Wendy's Dave's Single",                cat:'Fast Food', qty:1,   unit:'burger (226g)',    kcal:590, p:30, c:42, f:35  },
    { name:"Wendy's Frosty (small)",               cat:'Fast Food', qty:1,   unit:'cup (227g)',       kcal:310, p:8,  c:49, f:8   },
    { name:"Chick-fil-A Chicken Sandwich",         cat:'Fast Food', qty:1,   unit:'sandwich (165g)',  kcal:440, p:28, c:41, f:19  },
    { name:"Chick-fil-A Nuggets (8 pc)",           cat:'Fast Food', qty:8,   unit:'pieces (113g)',    kcal:260, p:28, c:11, f:12  },
    { name:"Subway 6\" Turkey Breast",             cat:'Fast Food', qty:1,   unit:'sub (231g)',       kcal:280, p:18, c:45, f:4.5 },
    { name:"Subway 6\" Chicken Teriyaki",          cat:'Fast Food', qty:1,   unit:'sub (253g)',       kcal:370, p:24, c:55, f:7   },
    { name:"Chipotle Chicken (scoop)",             cat:'Fast Food', qty:4,   unit:'oz (113g)',        kcal:180, p:32, c:0,  f:7   },
    { name:"Chipotle Steak (scoop)",               cat:'Fast Food', qty:4,   unit:'oz (113g)',        kcal:190, p:29, c:2,  f:7.5 },
    { name:"Chipotle Brown Rice (scoop)",          cat:'Fast Food', qty:4,   unit:'oz (113g)',        kcal:130, p:2,  c:23, f:3   },
    { name:"Chipotle Black Beans (scoop)",         cat:'Fast Food', qty:4,   unit:'oz (113g)',        kcal:120, p:7,  c:23, f:1   },
    { name:"Chipotle Sour Cream",                  cat:'Fast Food', qty:2,   unit:'oz (57g)',         kcal:120, p:2,  c:2,  f:11  },
    { name:"Chipotle Guacamole",                   cat:'Fast Food', qty:4,   unit:'oz (113g)',        kcal:230, p:2,  c:8,  f:22  },
    { name:"Chipotle Shredded Cheese",             cat:'Fast Food', qty:1,   unit:'oz (28g)',         kcal:100, p:6,  c:0.5,f:9   },
    { name:"Pizza Hut Pepperoni (medium slice)",   cat:'Fast Food', qty:1,   unit:'slice (103g)',     kcal:260, p:12, c:27, f:12  },
    { name:"Domino's Hand-Tossed Cheese (medium)", cat:'Fast Food', qty:1,   unit:'slice (97g)',      kcal:210, p:9,  c:29, f:7   },
    { name:"Taco Bell Chicken Taco",               cat:'Fast Food', qty:1,   unit:'taco (100g)',      kcal:170, p:12, c:15, f:7   },
    { name:"Taco Bell Bean Burrito",               cat:'Fast Food', qty:1,   unit:'burrito (198g)',   kcal:380, p:14, c:55, f:11  },
    { name:"Panda Express Orange Chicken",         cat:'Fast Food', qty:5.4, unit:'oz (153g)',        kcal:380, p:16, c:47, f:17  },
    { name:"Starbucks Latte, Grande (2%)",         cat:'Fast Food', qty:1,   unit:'grande (470ml)',   kcal:190, p:12, c:19, f:7   },
    { name:"Starbucks Caramel Macchiato, Grande",  cat:'Fast Food', qty:1,   unit:'grande (473ml)',   kcal:250, p:10, c:35, f:8   },

    /* ─── Meals & Prepared ──────────────────────────────────────────── */
    { name:'Chicken noodle soup',              cat:'Meals & Prepared', qty:1,   unit:'cup (240ml)',    kcal:75,  p:5,  c:9,  f:2.5 },
    { name:'Tomato soup (prepared)',           cat:'Meals & Prepared', qty:1,   unit:'cup (244g)',     kcal:85,  p:2,  c:17, f:2   },
    { name:'Beef chili, canned',              cat:'Meals & Prepared', qty:1,   unit:'cup (255g)',     kcal:250, p:17, c:30, f:7.5 },
    { name:'Clam chowder',                    cat:'Meals & Prepared', qty:1,   unit:'cup (244g)',     kcal:186, p:8,  c:18, f:9   },
    { name:'Minestrone soup',                 cat:'Meals & Prepared', qty:1,   unit:'cup (241g)',     kcal:82,  p:4,  c:14, f:1.5 },
    { name:'Lentil soup, canned',             cat:'Meals & Prepared', qty:1,   unit:'cup (243g)',     kcal:150, p:10, c:23, f:2.5 },
    { name:'Black bean soup',                 cat:'Meals & Prepared', qty:1,   unit:'cup (247g)',     kcal:218, p:13, c:39, f:1.5 },
    { name:'Split pea soup',                  cat:'Meals & Prepared', qty:1,   unit:'cup (253g)',     kcal:190, p:10, c:28, f:4   },
    { name:'Mac and cheese (boxed, prepared)',cat:'Meals & Prepared', qty:1,   unit:'cup (205g)',     kcal:370, p:10, c:48, f:15  },
    { name:'Instant ramen (chicken flavor)',  cat:'Meals & Prepared', qty:1,   unit:'packet (85g)',   kcal:380, p:9,  c:54, f:14  },
    { name:'Frozen burrito (bean & cheese)',  cat:'Meals & Prepared', qty:1,   unit:'burrito (148g)', kcal:340, p:11, c:51, f:11  },
    { name:'Frozen pizza, pepperoni',         cat:'Meals & Prepared', qty:1,   unit:'serving (131g)', kcal:330, p:14, c:36, f:15  },
    { name:'Egg fried rice',                  cat:'Meals & Prepared', qty:1,   unit:'cup (205g)',     kcal:280, p:9,  c:40, f:9   },
    { name:'Chicken fried rice',              cat:'Meals & Prepared', qty:1,   unit:'cup (198g)',     kcal:290, p:14, c:37, f:9   },
    { name:'Beef stew, canned',               cat:'Meals & Prepared', qty:1,   unit:'cup (232g)',     kcal:220, p:14, c:16, f:11  },
    { name:'Beef lo mein',                    cat:'Meals & Prepared', qty:1,   unit:'cup (198g)',     kcal:270, p:14, c:37, f:8   },
    { name:'Canned tuna (5 oz can)',          cat:'Meals & Prepared', qty:1,   unit:'can (142g)',     kcal:165, p:38, c:0,  f:1.4 },
    { name:'Canned salmon (6 oz)',            cat:'Meals & Prepared', qty:1,   unit:'can (170g)',     kcal:238, p:32, c:0,  f:12  },
    { name:'Pad Thai noodles',                cat:'Meals & Prepared', qty:1,   unit:'cup (227g)',     kcal:350, p:18, c:44, f:12  },
    { name:'French onion soup',               cat:'Meals & Prepared', qty:1,   unit:'cup (235g)',     kcal:57,  p:3,  c:8,  f:1.7 },

    /* ─── International ─────────────────────────────────────────────── */
    { name:'California Roll (6 pcs)',    cat:'International', qty:6,   unit:'pieces (135g)',    kcal:255, p:7,  c:38, f:7   },
    { name:'Salmon Nigiri (2 pcs)',      cat:'International', qty:2,   unit:'pieces (90g)',     kcal:130, p:8,  c:20, f:2   },
    { name:'Tuna Nigiri (2 pcs)',        cat:'International', qty:2,   unit:'pieces (86g)',     kcal:110, p:10, c:16, f:0.5 },
    { name:'Spicy Tuna Roll (6 pcs)',    cat:'International', qty:6,   unit:'pieces (135g)',    kcal:290, p:15, c:33, f:10  },
    { name:'Edamame (in pod)',           cat:'International', qty:1,   unit:'cup (120g)',       kcal:120, p:11, c:10, f:5   },
    { name:'Miso soup',                  cat:'International', qty:1,   unit:'cup (240ml)',      kcal:40,  p:3,  c:5,  f:1.5 },
    { name:'Pho (beef broth + noodles)', cat:'International', qty:1,   unit:'bowl (~500g)',     kcal:350, p:20, c:45, f:7   },
    { name:'Tom Yum soup',               cat:'International', qty:1,   unit:'cup (240g)',       kcal:90,  p:8,  c:8,  f:3   },
    { name:'Chicken Tikka Masala',       cat:'International', qty:1,   unit:'cup (244g)',       kcal:320, p:28, c:16, f:17  },
    { name:'Palak Paneer',               cat:'International', qty:1,   unit:'cup (244g)',       kcal:270, p:12, c:14, f:20  },
    { name:'Dal (red lentil)',           cat:'International', qty:1,   unit:'cup (244g)',       kcal:200, p:12, c:30, f:5   },
    { name:'Falafel',                    cat:'International', qty:3,   unit:'pieces (75g)',     kcal:200, p:7,  c:19, f:11  },
    { name:'Chicken Shawarma',           cat:'International', qty:100, unit:'g',                kcal:190, p:20, c:5,  f:10  },
    { name:'Beef Shawarma',              cat:'International', qty:100, unit:'g',                kcal:210, p:22, c:5,  f:12  },
    { name:'Chicken Gyro',               cat:'International', qty:100, unit:'g',                kcal:185, p:20, c:5,  f:10  },
    { name:'Greek Salad (no dressing)',  cat:'International', qty:1.5, unit:'cups (180g)',      kcal:90,  p:3,  c:9,  f:5   },
    { name:'Tacos al Pastor (2)',        cat:'International', qty:2,   unit:'tacos (150g)',     kcal:360, p:20, c:34, f:15  },
    { name:'Chicken Enchilada',          cat:'International', qty:1,   unit:'enchilada (130g)', kcal:330, p:18, c:28, f:16  },
    { name:'Beef Burrito (large)',       cat:'International', qty:1,   unit:'burrito (305g)',   kcal:760, p:36, c:90, f:27  },
    { name:'Kimchi Fried Rice',          cat:'International', qty:1,   unit:'cup (200g)',       kcal:290, p:9,  c:42, f:9   },
    { name:'Bibimbap (full bowl)',       cat:'International', qty:1,   unit:'bowl (450g)',      kcal:490, p:22, c:72, f:14  },
    { name:"General Tso's Chicken",      cat:'International', qty:1,   unit:'cup (153g)',       kcal:400, p:21, c:39, f:18  },

    /* ─── Brands ────────────────────────────────────────────────────── */
    { name:'Quest Bar (Chocolate Chip)',     cat:'Brands', qty:1,   unit:'bar (60g)',       kcal:200, p:21, c:22, f:8   },
    { name:'RXBAR (Chocolate Sea Salt)',     cat:'Brands', qty:1,   unit:'bar (52g)',       kcal:210, p:12, c:24, f:9   },
    { name:'Clif Bar',                       cat:'Brands', qty:1,   unit:'bar (68g)',       kcal:250, p:9,  c:45, f:6   },
    { name:'Built Bar',                      cat:'Brands', qty:1,   unit:'bar (49g)',       kcal:130, p:17, c:18, f:4   },
    { name:'Perfect Bar (Peanut Butter)',    cat:'Brands', qty:1,   unit:'bar (67g)',       kcal:330, p:16, c:23, f:21  },
    { name:'KIND Bar (Almond & Coconut)',    cat:'Brands', qty:1,   unit:'bar (40g)',       kcal:200, p:4,  c:16, f:14  },
    { name:'Nature Valley Granola Bars',     cat:'Brands', qty:2,   unit:'bars (42g)',      kcal:190, p:4,  c:29, f:7   },
    { name:'Larabar (Cashew Cookie)',        cat:'Brands', qty:1,   unit:'bar (48g)',       kcal:220, p:5,  c:25, f:12  },
    { name:'Premier Protein Shake',         cat:'Brands', qty:1,   unit:'shake (325ml)',   kcal:160, p:30, c:4,  f:3   },
    { name:'Fairlife Core Power (26g)',      cat:'Brands', qty:1,   unit:'bottle (414ml)',  kcal:170, p:26, c:8,  f:4.5 },
    { name:'Muscle Milk Genuine',            cat:'Brands', qty:1,   unit:'shake (330ml)',   kcal:160, p:25, c:9,  f:4   },
    { name:'Optimum Nutrition Gold Whey',    cat:'Brands', qty:1,   unit:'scoop (31g)',     kcal:120, p:24, c:3,  f:1.5 },
    { name:'Chobani Nonfat Greek Yogurt',    cat:'Brands', qty:1,   unit:'cup (150g)',      kcal:90,  p:16, c:6,  f:0   },
    { name:'Fage Total 0%',                  cat:'Brands', qty:1,   unit:'cup (170g)',      kcal:90,  p:18, c:5,  f:0   },
    { name:'Oikos Triple Zero',              cat:'Brands', qty:1,   unit:'cup (150g)',      kcal:90,  p:15, c:8,  f:0   },
    { name:'Siggis 4% Plain Yogurt',         cat:'Brands', qty:1,   unit:'cup (170g)',      kcal:180, p:18, c:15, f:5   },
    { name:'Two Good Yogurt',                cat:'Brands', qty:1,   unit:'cup (150g)',      kcal:80,  p:12, c:3,  f:2   },
    { name:'Fairlife 2% Milk',               cat:'Brands', qty:1,   unit:'cup (240ml)',     kcal:80,  p:13, c:6,  f:2.5 },
    { name:'Good Culture Cottage Cheese',    cat:'Brands', qty:0.5, unit:'cup (113g)',      kcal:90,  p:14, c:4,  f:2.5 },
    { name:'Halo Top (Vanilla)',             cat:'Brands', qty:0.5, unit:'cup (66g)',       kcal:90,  p:5,  c:14, f:3   },
    { name:'Kodiak Cakes (pancake mix)',     cat:'Brands', qty:0.5, unit:'cup dry (53g)',   kcal:190, p:14, c:30, f:3   },
    { name:'Quaker Instant Oatmeal',         cat:'Brands', qty:1,   unit:'packet (28g)',    kcal:100, p:4,  c:19, f:2   },
    { name:"Dave's Killer Bread (21 Grain)", cat:'Brands', qty:1,   unit:'slice (45g)',     kcal:110, p:5,  c:22, f:1.5 },
    { name:'Skippy Peanut Butter',           cat:'Brands', qty:2,   unit:'tbsp (32g)',      kcal:190, p:7,  c:7,  f:16  },
    { name:"Justin's Almond Butter",         cat:'Brands', qty:2,   unit:'tbsp (32g)',      kcal:190, p:7,  c:6,  f:16  },
    { name:'Banza Chickpea Pasta',           cat:'Brands', qty:2,   unit:'oz dry (57g)',    kcal:190, p:14, c:32, f:3.5 },
    { name:'Quest Protein Chips',            cat:'Brands', qty:1,   unit:'bag (32g)',       kcal:140, p:19, c:5,  f:4.5 },
    { name:"Rao's Marinara Sauce",           cat:'Brands', qty:0.5, unit:'cup (125g)',      kcal:80,  p:2,  c:9,  f:4   },
    { name:"Amy's Lentil Soup",              cat:'Brands', qty:1,   unit:'cup (243g)',      kcal:150, p:10, c:23, f:2.5 },
    { name:'Kirkland Rotisserie Chicken',    cat:'Brands', qty:3,   unit:'oz (85g)',        kcal:140, p:24, c:0,  f:5.5 },
  ];

  // Assign stable IDs
  F.forEach((x, i) => { x.id = 'f' + (i + 1); });
  window.FOOD_DB = F;
})();
