// Generated from PeakFormBio-Products-Protocols.csv (BAC, Dose, Units, Frequency, Cycle, Size of Syringe).
// Edit values here to change calculator presets.
window.RECON_PRESETS = [
 {
  "id": "ara-290-10mg",
  "name": "ARA-290 — 10mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 40,
  "doseText": "4mg",
  "frequency": "Daily",
  "cycle": "28 Days",
  "syringe": 0.5
 },
 {
  "id": "dsip-10mg",
  "name": "DSIP — 10mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg",
  "frequency": "5on/2off",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "dsip-15mg",
  "name": "DSIP — 15mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 15,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "500mcg",
  "frequency": "5on/2off",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "selank-10mg",
  "name": "Selank — 10mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg",
  "frequency": "2x/3x Week",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "selank-30mg",
  "name": "Selank — 30mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 30,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "1mg",
  "frequency": "2x/3x Week",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "semax-10mg",
  "name": "Semax — 10mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg",
  "frequency": "2x/3x Week",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "semax-30mg",
  "name": "Semax — 30mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 30,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "1mg",
  "frequency": "2x/3x Week",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "semax-selank-blend-20mg",
  "name": "Semax-Selank Blend — 20mg",
  "category": "Cognitive / Mood / Sleep",
  "vial": 20,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg+500mcg",
  "frequency": "2x/3x Week",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "bpc-10mg",
  "name": "BPC — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg",
  "frequency": "1x/2x Day",
  "cycle": "8 Weeks",
  "syringe": 0.5
 },
 {
  "id": "btk-30mg",
  "name": "BTK — 30mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 30,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "1.6mg/.33mg/33mg",
  "frequency": "Daily",
  "cycle": "4-6 Weeks",
  "syringe": 0.3
 },
 {
  "id": "cartalax-10mg",
  "name": "Cartalax — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 10,
  "doseText": "1mg",
  "frequency": "Daily",
  "cycle": "10 Days",
  "syringe": 0.3
 },
 {
  "id": "cjc-1295-dac-5mg",
  "name": "CJC 1295 DAC — 5mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 5,
  "vialUnit": "mg",
  "bac": 1,
  "units": 10,
  "doseText": "1mg",
  "frequency": "2x Week",
  "cycle": "12-16 Weeks",
  "syringe": 0.3
 },
 {
  "id": "ghrp-2-10mg",
  "name": "GHRP-2 — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "333mcg",
  "frequency": "2x/3x Day",
  "cycle": "5on/2off",
  "syringe": 0.3
 },
 {
  "id": "ghrp-6-10mg",
  "name": "GHRP-6 — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "333mcg",
  "frequency": "2x/3x Day",
  "cycle": "5on/2off",
  "syringe": 0.3
 },
 {
  "id": "glow-70mg",
  "name": "GLOW — 70mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 70,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "1.6mg/.33mg/33mg/.33mg",
  "frequency": "Daily",
  "cycle": "4-6 Weeks",
  "syringe": 0.3
 },
 {
  "id": "hair-growth-helper-10iu",
  "name": "Hair Growth Helper — 10IU",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "IU",
  "bac": 1,
  "units": 20,
  "doseText": "2iu",
  "frequency": "Nightly",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "hair-growth-helper-36iu",
  "name": "Hair Growth Helper — 36IU",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 36,
  "vialUnit": "IU",
  "bac": 3.5,
  "units": 40,
  "doseText": "4iu",
  "frequency": "Nightly",
  "cycle": "None",
  "syringe": 0.5
 },
 {
  "id": "igf-lr3-1mg",
  "name": "IGF LR3 — 1mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 1,
  "vialUnit": "mg",
  "bac": 2.5,
  "units": 10,
  "doseText": "40mcg",
  "frequency": "Daily",
  "cycle": "10 Days",
  "syringe": 0.3
 },
 {
  "id": "ipamorelin-10mg",
  "name": "Ipamorelin — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "333mcg",
  "frequency": "Nightly",
  "cycle": "8-12 Weeks",
  "syringe": 0.3
 },
 {
  "id": "klow-80mg",
  "name": "KLOW — 80mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 80,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "1.6mg/.33mg/33mg/.33mg",
  "frequency": "Daily",
  "cycle": "4-6 Weeks",
  "syringe": 0.3
 },
 {
  "id": "tb-500-10mg",
  "name": "TB-500 — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg",
  "frequency": "2x Week",
  "cycle": "4-12 Weeks",
  "syringe": 0.3
 },
 {
  "id": "tesamorelin-10mg",
  "name": "Tesamorelin — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 20,
  "doseText": "2mg",
  "frequency": "Daily",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "wolverine-10mg",
  "name": "Wolverine — 10mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 10,
  "doseText": "500mcg+500mcg",
  "frequency": "Daily",
  "cycle": "6-12 Weeks",
  "syringe": 0.3
 },
 {
  "id": "wolverine-20mg",
  "name": "Wolverine — 20mg",
  "category": "Growth Hormone / Recovery / Muscle",
  "vial": 20,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg+500mcg",
  "frequency": "Daily",
  "cycle": "6-12 Weeks",
  "syringe": 0.3
 },
 {
  "id": "hcg-10000iu",
  "name": "HCG — 10000IU",
  "category": "Hormonal / Sexual Wellness",
  "vial": 10000,
  "vialUnit": "IU",
  "bac": 3.5,
  "units": 9,
  "doseText": "250iu",
  "frequency": "2x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "hcg-5000iu",
  "name": "HCG — 5000IU",
  "category": "Hormonal / Sexual Wellness",
  "vial": 5000,
  "vialUnit": "IU",
  "bac": 2,
  "units": 10,
  "doseText": "250iu",
  "frequency": "2x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "pt-141-10mg",
  "name": "PT-141 — 10mg",
  "category": "Hormonal / Sexual Wellness",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 20,
  "doseText": "2mg",
  "frequency": "2x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "epithalon-50mg",
  "name": "Epithalon — 50mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 50,
  "vialUnit": "mg",
  "bac": 2.5,
  "units": 50,
  "doseText": "10mg",
  "frequency": "Daily",
  "cycle": "10 Days/2x Year",
  "syringe": 0.5
 },
 {
  "id": "mito-magic-120mg",
  "name": "Mito Magic — 120mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 120,
  "vialUnit": "mg",
  "bac": 3,
  "units": 50,
  "doseText": "20mg",
  "frequency": "2x Week",
  "cycle": "6-8 Weeks",
  "syringe": 0.5
 },
 {
  "id": "mots-c-10mg",
  "name": "MOTS-c — 10mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 50,
  "doseText": "5mg",
  "frequency": "2x/3x Week",
  "cycle": "4-8 Weeks",
  "syringe": 0.5
 },
 {
  "id": "mots-c-40mg",
  "name": "MOTS-c — 40mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 40,
  "vialUnit": "mg",
  "bac": 2,
  "units": 25,
  "doseText": "5mg",
  "frequency": "2x/3x Week",
  "cycle": "4-8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "nad-1000mg",
  "name": "NAD+ — 1000mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 1000,
  "vialUnit": "mg",
  "bac": 5,
  "units": 50,
  "doseText": "100mg",
  "frequency": "2x/3x Week",
  "cycle": "None",
  "syringe": 0.5
 },
 {
  "id": "nad-500mg",
  "name": "NAD+ — 500mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 500,
  "vialUnit": "mg",
  "bac": 5,
  "units": 100,
  "doseText": "100mg",
  "frequency": "2x/3x Week",
  "cycle": "None",
  "syringe": 1
 },
 {
  "id": "ss-31-50mg",
  "name": "SS-31 — 50mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 50,
  "vialUnit": "mg",
  "bac": 2.5,
  "units": 25,
  "doseText": "5mg",
  "frequency": "Daily",
  "cycle": "4-8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "thymosin-alpha-1-10mg",
  "name": "Thymosin Alpha 1 — 10mg",
  "category": "Longevity / Cellular Health / Mitochondrial",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 2,
  "units": 32,
  "doseText": "1.6mg",
  "frequency": "2x Week",
  "cycle": "6-12 Months",
  "syringe": 0.3
 },
 {
  "id": "5-amino-50mg",
  "name": "5 Amino — 50mg",
  "category": "Metabolic / Weight Management",
  "vial": 50,
  "vialUnit": "mg",
  "bac": 2.5,
  "units": 25,
  "doseText": "5mg",
  "frequency": "2x/3x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "cagrilintide-10mg",
  "name": "Cagrilintide — 10mg",
  "category": "Metabolic / Weight Management",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 3.5,
  "units": 10,
  "doseText": "250mcg",
  "frequency": "3x Week",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-10mg",
  "name": "Retatrutide — 10mg",
  "category": "Metabolic / Weight Management",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "2.5mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-12mg",
  "name": "Retatrutide — 12mg",
  "category": "Metabolic / Weight Management",
  "vial": 12,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "3mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-15mg",
  "name": "Retatrutide — 15mg",
  "category": "Metabolic / Weight Management",
  "vial": 15,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "3.5mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-20mg",
  "name": "Retatrutide — 20mg",
  "category": "Metabolic / Weight Management",
  "vial": 20,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "5mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-30mg",
  "name": "Retatrutide — 30mg",
  "category": "Metabolic / Weight Management",
  "vial": 30,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "7.5mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-40mg",
  "name": "Retatrutide — 40mg",
  "category": "Metabolic / Weight Management",
  "vial": 40,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "10mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-5mg",
  "name": "Retatrutide — 5mg",
  "category": "Metabolic / Weight Management",
  "vial": 5,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "1.25mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "retatrutide-60mg",
  "name": "Retatrutide — 60mg",
  "category": "Metabolic / Weight Management",
  "vial": 60,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "15mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "tirzepatide-10mg",
  "name": "Tirzepatide — 10mg",
  "category": "Metabolic / Weight Management",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "2.5mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "tirzepatide-20mg",
  "name": "Tirzepatide — 20mg",
  "category": "Metabolic / Weight Management",
  "vial": 20,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "5mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "tirzepatide-30mg",
  "name": "Tirzepatide — 30mg",
  "category": "Metabolic / Weight Management",
  "vial": 30,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "7.5mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "tirzepatide-40mg",
  "name": "Tirzepatide — 40mg",
  "category": "Metabolic / Weight Management",
  "vial": 40,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "10mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "tirzepatide-60mg",
  "name": "Tirzepatide — 60mg",
  "category": "Metabolic / Weight Management",
  "vial": 60,
  "vialUnit": "mg",
  "bac": 1,
  "units": 25,
  "doseText": "15mg",
  "frequency": "1x Week",
  "cycle": "None",
  "syringe": 0.3
 },
 {
  "id": "ghk-cu-100mg",
  "name": "GHK-Cu — 100mg",
  "category": "Skin / Beauty / Anti-Aging",
  "vial": 100,
  "vialUnit": "mg",
  "bac": 2.5,
  "units": 5,
  "doseText": "2mg",
  "frequency": "Daily",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "ghk-cu-50mg",
  "name": "GHK-Cu — 50mg",
  "category": "Skin / Beauty / Anti-Aging",
  "vial": 50,
  "vialUnit": "mg",
  "bac": 2.5,
  "units": 10,
  "doseText": "2mg",
  "frequency": "Daily",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "kpv-10mg",
  "name": "KPV — 10mg",
  "category": "Skin / Beauty / Anti-Aging",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 2,
  "units": 10,
  "doseText": "500mcg",
  "frequency": "5on/2off",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "kpv-30mg",
  "name": "KPV — 30mg",
  "category": "Skin / Beauty / Anti-Aging",
  "vial": 30,
  "vialUnit": "mg",
  "bac": 3,
  "units": 10,
  "doseText": "1mg",
  "frequency": "5on/2off",
  "cycle": "8 Weeks",
  "syringe": 0.3
 },
 {
  "id": "melanotan-1-10mg",
  "name": "Melanotan 1 — 10mg",
  "category": "Skin / Beauty / Anti-Aging",
  "vial": 10,
  "vialUnit": "mg",
  "bac": 3.5,
  "units": 10,
  "doseText": "250mcg/500mcg",
  "frequency": "2x Week",
  "cycle": "None",
  "syringe": 0.3
 }
];

// Shared helpers (calculator + admin editor).
window.reconDoseOf = function (p) {
  if (p.doseAmt > 0 && p.doseUnit) return { amt: +p.doseAmt, unit: p.doseUnit };
  var amt = (p.units / 100) * (p.vial / p.bac); // mg or IU implied by sheet's draw units
  if (p.vialUnit === 'IU') return { amt: +amt.toFixed(2), unit: 'IU' };
  if (amt >= 1) return { amt: +amt.toFixed(3), unit: 'mg' };
  return { amt: Math.round(amt * 1000), unit: 'mcg' };
};
window.reconUnitsFor = function (vial, vialUnit, bac, doseAmt, doseUnit) {
  var d = vialUnit === 'IU' ? doseAmt : (doseUnit === 'mg' ? doseAmt : doseAmt / 1000);
  if (!(vial > 0 && bac > 0 && d > 0)) return 0;
  return (d / (vial / bac)) * 100;
};
window.reconSyringeFor = function (units, preferred) {
  var sizes = [0.3, 0.5, 1];
  if (preferred && units <= preferred * 100) return preferred;
  for (var i = 0; i < sizes.length; i++) if (units <= sizes[i] * 100) return sizes[i];
  return 1;
};
// Admin-edited presets (saved on the server) replace the defaults above.
window.loadReconPresets = function () {
  return fetch('/api/public/recon-presets').then(function (r) { return r.ok ? r.json() : null; })
    .then(function (list) { if (Array.isArray(list) && list.length) window.RECON_PRESETS = list; return window.RECON_PRESETS; })
    .catch(function () { return window.RECON_PRESETS; });
};
