/* ────────────────────────────────────────────────────────────────────────────
   PeakForm Bio — Peptide Library data
   Categorization mirrors common goal-based peptide references (Peptadex et al.).
   All entries are factual summaries compiled from research literature and public
   sources, written in-house. NOT copied verbatim from any third-party site.
   Educational / research use only — not medical advice.
   ──────────────────────────────────────────────────────────────────────────── */
(function () {
  window.PEPTIDE_CATEGORIES = [
    { key: 'healing',        label: 'Healing & Recovery' },
    { key: 'skin',           label: 'Skin & Hair' },
    { key: 'growth_hormone', label: 'Growth Hormone' },
    { key: 'weight_loss',    label: 'Weight Loss' },
    { key: 'cognitive',      label: 'Cognitive' },
    { key: 'immune',         label: 'Immune' },
    { key: 'anti_aging',     label: 'Anti-Aging & Longevity' },
    { key: 'hormonal',       label: 'Hormonal' },
    { key: 'metabolic',      label: 'Metabolic' },
    { key: 'pain',           label: 'Pain & Analgesic' },
  ];

  window.PEPTIDE_PHASES = ['FDA Approved', 'Phase 3', 'Phase 2', 'Phase 1', 'Preclinical'];

  // dosing fields: dose, frequency, route, timing, food, duration, range, notes
  const P = [

    /* ─── HEALING & RECOVERY ─────────────────────────────────────────────── */
    {
      slug: 'bpc-157', name: 'BPC-157', category: 'healing', phase: 'Preclinical',
      aka: ['Body Protection Compound 157', 'Pentadecapeptide BPC 157'], sequence: 'GEPPPGKPADDAGLV',
      overview: 'Synthetic 15-amino-acid fragment derived from a protein in human gastric juice. Studied extensively in animals for tissue healing.',
      status: 'Preclinical. Placed on the FDA Category 2 bulk-substance list in Sep 2023 (restricted from compounding). Human data limited to a few small pilot studies.',
      mechanism: 'Modulates the nitric-oxide system, promotes angiogenesis (new blood-vessel formation), upregulates growth-hormone receptor expression, and interacts with the dopaminergic system. Animal work reports accelerated tendon-, ligament-, and gut-tissue repair.',
      benefits: ['May accelerate tendon, ligament, and muscle healing', 'Associated with gut-lining repair in animal models', 'Promotes new blood-vessel formation at injury sites', 'May reduce inflammation and oxidative stress', 'Studied for neuroprotective effects in animals'],
      dosing: { dose: '250–500 mcg', frequency: '1–2× daily', route: 'Subcutaneous injection (often near injury), or oral', timing: 'Morning and evening', food: 'With or without', duration: '4–12 weeks', range: '200–1,000 mcg/day total', notes: 'Split dosing maintains stable levels. Frequently stacked with TB-500 in community protocols; no human combination trials exist.' },
      sideEffects: ['Injection-site irritation', 'Occasional nausea', 'Dizziness', 'Fatigue', 'Headache'],
      warnings: ['Theoretical caution with active cancer (promotes angiogenesis — unproven in humans)', 'FDA Category 2 — restricted from compounding', 'Not medical advice'],
    },
    {
      slug: 'tb-500', name: 'TB-500', category: 'healing', phase: 'Preclinical', aka: ['Thymosin Beta-4 Fragment'],
      overview: 'A synthetic fragment of the naturally occurring protein Thymosin Beta-4, used in research for tissue repair and recovery.',
      status: 'Preclinical. On the FDA July 2026 PCAC review agenda. No completed Phase 3 human trials.',
      mechanism: 'Regulates actin, a cell-building protein, promoting cell migration, blood-vessel growth, and tissue remodeling. Animal studies report improved wound healing and reduced inflammation/scarring.',
      benefits: ['May support muscle, tendon, and ligament recovery', 'Promotes cell migration to injury sites', 'May reduce inflammation and adhesions/scarring', 'Studied for cardiac tissue repair'],
      dosing: { dose: '2–2.5 mg', frequency: '2× weekly (loading), then weekly', route: 'Subcutaneous injection', timing: 'Any', food: 'With or without', duration: '4–8 week loading, then maintenance', range: '2–5 mg/week', notes: 'Often paired with BPC-157 for connective-tissue protocols. Loading phase then taper is common in anecdotal use.' },
      sideEffects: ['Injection-site reactions', 'Head-rush / lightheadedness shortly after dosing', 'Fatigue'],
      warnings: ['WADA-prohibited in sport', 'Theoretical caution with active malignancy', 'Not medical advice'],
    },
    {
      slug: 'pentadecapeptide', name: 'Pentadecapeptide', category: 'healing', phase: 'Preclinical', aka: ['BPC-157 arginate'],
      overview: 'Research peptide studied for wound healing and tissue regeneration; closely related to the BPC-157 family.',
      mechanism: 'A stable-salt form of the body-protection pentadecapeptide; proposed to share BPC-157\u2019s angiogenic and cytoprotective actions on connective and gut tissue.',
      benefits: ['Studied for tendon, ligament, and gut healing', 'Cytoprotective and angiogenic activity in animal models'],
      dosing: { dose: '250–500 mcg', frequency: '1–2× daily', route: 'Subcutaneous or oral', timing: 'Morning / evening', food: 'With or without', duration: '4–12 weeks', range: '250–1,000 mcg/day', notes: 'Used interchangeably with BPC-157 in many anecdotal protocols.' },
      sideEffects: ['Injection-site irritation', 'Mild nausea'],
      warnings: ['Preclinical — human evidence limited', 'Not medical advice'],
    },
    {
      slug: 'thymosin-beta-4', name: 'Thymosin Beta-4', category: 'healing', phase: 'Phase 2', aka: ['Tβ4'],
      overview: 'The full-length 43-amino-acid thymosin protein investigated for wound healing and cardiac tissue repair.',
      mechanism: 'Sequesters actin and promotes cell migration, angiogenesis, and survival of repair cells; the parent molecule of TB-500.',
      benefits: ['Wound and corneal healing research', 'Cardiac repair after ischemia (animal models)', 'Anti-inflammatory and anti-fibrotic signaling'],
      dosing: { dose: '2–5 mg', frequency: '2–3× weekly', route: 'Subcutaneous injection', timing: 'Any', food: 'With or without', duration: '4–8 weeks', range: '2–10 mg/week', notes: 'Full-length protein; research dosing parallels TB-500.' },
      sideEffects: ['Injection-site reactions', 'Lightheadedness', 'Fatigue'],
      warnings: ['Caution with active malignancy', 'Not medical advice'],
    },
    {
      slug: 'ghk', name: 'GHK', category: 'healing', phase: 'Phase 2', aka: ['Glycyl-L-Histidyl-L-Lysine'],
      overview: 'Naturally occurring tripeptide for tissue remodeling — the copper-free counterpart of GHK-Cu.',
      mechanism: 'Signals collagen, elastin, and glycosaminoglycan synthesis and helps reset gene expression toward a younger, repair-oriented state; binds copper in the body to form GHK-Cu.',
      benefits: ['Supports skin and connective-tissue remodeling', 'Antioxidant and anti-inflammatory signaling', 'May aid wound healing'],
      dosing: { dose: 'Topical 1–2%, or research SubQ', frequency: 'Daily (topical)', route: 'Topical or subcutaneous', timing: 'AM/PM', food: 'N/A', duration: 'Ongoing', range: '1–2% topical', notes: 'Most human use is topical/cosmetic.' },
      sideEffects: ['Mild skin irritation'],
      warnings: ['Patch-test topical products', 'Not medical advice'],
    },
    {
      slug: 'cerebrolysin', name: 'Cerebrolysin', category: 'healing', phase: 'Phase 3',
      overview: 'Neurotrophic peptide mixture used for neurological recovery. Approved in several countries outside the US.',
      status: 'Approved in numerous countries (e.g. for stroke, dementia, TBI). Not FDA-approved.',
      mechanism: 'A mixture of low-molecular-weight neuropeptides and amino acids with neurotrophic activity that mimics nerve growth factors and supports neuronal survival and plasticity.',
      benefits: ['Studied for stroke and traumatic brain injury recovery', 'Researched for vascular dementia and Alzheimer\u2019s', 'Neuroprotective and neurotrophic signaling'],
      dosing: { dose: '5–10 mL', frequency: 'Daily in courses', route: 'Intravenous or intramuscular', timing: 'Daytime', food: 'N/A', duration: '10–20 day courses', range: '5–30 mL/day (clinical)', notes: 'Administered clinically; dosing varies widely by indication.' },
      sideEffects: ['Injection-site reactions', 'Dizziness', 'Agitation if infused too quickly'],
      warnings: ['Not FDA-approved', 'Use under medical supervision', 'Not medical advice'],
    },
    {
      slug: 'collagen-peptides', name: 'Collagen Peptides', category: 'healing', phase: 'Phase 2', aka: ['Hydrolyzed collagen'],
      overview: 'Hydrolyzed collagen taken orally to support joint, skin, and connective-tissue health.',
      mechanism: 'Provides bioavailable glycine/proline/hydroxyproline peptides that act as building blocks and may signal fibroblasts to increase collagen synthesis.',
      benefits: ['Supports skin elasticity and hydration', 'May reduce joint discomfort', 'Connective-tissue and bone support'],
      dosing: { dose: '10–15 g', frequency: 'Once daily', route: 'Oral powder', timing: 'Any', food: 'With or without', duration: 'Ongoing', range: '2.5–15 g/day', notes: 'Sold as a food supplement; very well tolerated.' },
      sideEffects: ['Mild digestive upset', 'Fullness'],
      warnings: ['Check source for allergens (bovine/marine)', 'Not medical advice'],
    },
    {
      slug: 'elastin-peptides', name: 'Elastin Peptides', category: 'healing', phase: 'Preclinical',
      overview: 'Hydrolyzed elastin supplement researched for skin elasticity and vascular health.',
      mechanism: 'Supplies soluble elastin-derived peptides that may support elastic-fiber maintenance in skin and blood-vessel walls.',
      benefits: ['Studied for skin elasticity', 'Vascular elastic-tissue support'],
      dosing: { dose: '75–300 mg', frequency: 'Once daily', route: 'Oral', timing: 'Any', food: 'With or without', duration: 'Ongoing', range: '75–300 mg/day', notes: 'Usually combined with collagen in cosmetic supplements.' },
      sideEffects: ['Generally well tolerated'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'palmitoyl-pentapeptide-4', name: 'Palmitoyl Pentapeptide-4', category: 'healing', phase: 'Phase 2', aka: ['Matrixyl', 'Pal-KTTKS'],
      overview: 'Lipopeptide that signals collagen production; used topically for tissue repair and skin rejuvenation.',
      mechanism: 'A fatty-acid-linked peptide fragment of collagen that signals fibroblasts to rebuild collagen and extracellular matrix; the palmitoyl tail aids skin penetration.',
      benefits: ['Stimulates collagen I, III, and IV', 'Reduces fine lines with topical use', 'Improves skin texture'],
      dosing: { dose: 'Topical 2–8 ppm', frequency: 'Daily (AM/PM)', route: 'Topical serum/cream', timing: 'Skincare routine', food: 'N/A', duration: 'Ongoing', range: '2–8 ppm in formulation', notes: 'Cosmetic ingredient; effects build over weeks.' },
      sideEffects: ['Rare mild irritation'],
      warnings: ['Patch-test new products', 'Not medical advice'],
    },
    {
      slug: 'copper-peptide-complex', name: 'Copper Peptide Complex', category: 'healing', phase: 'Phase 2',
      overview: 'Copper-bound peptide complex studied for advanced wound healing and tissue remodeling.',
      mechanism: 'Delivers bioavailable copper alongside signaling peptides to drive collagen/elastin synthesis, angiogenesis, and antioxidant defense in healing tissue.',
      benefits: ['Wound-healing support', 'Collagen and elastin remodeling', 'Antioxidant activity'],
      dosing: { dose: 'Topical 1–2%', frequency: 'Daily', route: 'Topical', timing: 'AM/PM', food: 'N/A', duration: 'Ongoing', range: '1–2% topical', notes: 'Avoid layering with strong acids/vitamin C in the same step.' },
      sideEffects: ['Mild irritation', 'Temporary skin tint'],
      warnings: ['Patch-test', 'Not medical advice'],
    },

    /* ─── SKIN & HAIR ────────────────────────────────────────────────────── */
    {
      slug: 'ghk-cu', name: 'GHK-Cu', category: 'skin', phase: 'Phase 2', aka: ['Copper Tripeptide-1'],
      overview: 'Naturally occurring copper-binding tripeptide widely used in skincare for wound healing and anti-aging.',
      mechanism: 'Delivers copper to cells, stimulates collagen, elastin, and glycosaminoglycan synthesis, and has antioxidant and anti-inflammatory activity. Declines naturally with age.',
      benefits: ['Stimulates collagen and elastin production', 'Improves skin firmness and reduces fine lines', 'Supports wound healing', 'May support hair-follicle health'],
      dosing: { dose: 'Topical 1–2% (cosmetic) or research SubQ', frequency: 'Daily (topical)', route: 'Topical serum, or subcutaneous in research', timing: 'AM/PM skincare', food: 'N/A', duration: 'Ongoing', range: '1–2% topical', notes: 'Most evidence is for topical cosmetic use. Avoid combining with strong vitamin C in the same routine.' },
      sideEffects: ['Mild skin irritation', 'Redness at application site'],
      warnings: ['Patch-test topical products', 'Not medical advice'],
    },
    {
      slug: 'snap-8', name: 'SNAP-8', category: 'skin', phase: 'Phase 2', aka: ['Acetyl Octapeptide-3'],
      overview: 'Topical peptide that reduces wrinkle depth by relaxing facial muscle contraction.',
      mechanism: 'A peptide that competes with the SNARE complex involved in neurotransmitter release at the neuromuscular junction, gently reducing muscle contraction that causes expression lines.',
      benefits: ['Softens expression wrinkles topically', 'Needle-free "relaxing" alternative concept', 'Smoother forehead/eye-area appearance'],
      dosing: { dose: 'Topical 3–10%', frequency: 'Daily (AM/PM)', route: 'Topical serum', timing: 'Skincare routine', food: 'N/A', duration: 'Ongoing', range: '3–10% in formulation', notes: 'Cosmetic ingredient; results are gradual and reversible.' },
      sideEffects: ['Rare mild irritation'],
      warnings: ['Topical use only', 'Not medical advice'],
    },
    {
      slug: 'argireline', name: 'Argireline', category: 'skin', phase: 'Phase 2', aka: ['Acetyl Hexapeptide-8'],
      overview: 'Topical peptide for wrinkle reduction, often nicknamed "Botox in a bottle."',
      mechanism: 'Interferes with SNARE-complex formation to mildly limit the muscle contractions that drive expression lines — a topical, far milder analog of neuromodulator injections.',
      benefits: ['Reduces appearance of expression lines', 'Improves skin smoothness', 'Well tolerated topically'],
      dosing: { dose: 'Topical 5–10%', frequency: 'Daily (AM/PM)', route: 'Topical serum', timing: 'Skincare routine', food: 'N/A', duration: 'Ongoing', range: '5–10% in formulation', notes: 'Cosmetic ingredient; effects build over weeks and are reversible.' },
      sideEffects: ['Rare irritation or dryness'],
      warnings: ['Topical use only', 'Not medical advice'],
    },
    {
      slug: 'matrixyl', name: 'Matrixyl', category: 'skin', phase: 'Phase 2', aka: ['Palmitoyl Pentapeptide / Tripeptide blends'],
      overview: 'Lipopeptide that stimulates collagen production, used in anti-aging skincare.',
      mechanism: 'Matrikine peptides linked to a palmitoyl tail signal fibroblasts to rebuild collagen and extracellular-matrix proteins, with improved skin penetration.',
      benefits: ['Boosts collagen synthesis', 'Reduces wrinkle depth', 'Improves firmness and hydration'],
      dosing: { dose: 'Topical 3–8%', frequency: 'Daily (AM/PM)', route: 'Topical serum/cream', timing: 'Skincare routine', food: 'N/A', duration: 'Ongoing', range: '3–8% in formulation', notes: 'One of the best-studied cosmetic anti-aging peptides.' },
      sideEffects: ['Rare mild irritation'],
      warnings: ['Topical use only', 'Not medical advice'],
    },
    {
      slug: 'palmitoyl-tripeptide-1', name: 'Palmitoyl Tripeptide-1', category: 'skin', phase: 'Phase 2', aka: ['Pal-GHK'],
      overview: 'Collagen-stimulating lipopeptide used in anti-aging skincare formulations.',
      mechanism: 'A palmitoylated GHK matrikine that signals collagen and glycosaminoglycan production in the dermis.',
      benefits: ['Stimulates collagen', 'Improves skin tone and elasticity', 'Often paired with Palmitoyl Tetrapeptide-7'],
      dosing: { dose: 'Topical (trace %)', frequency: 'Daily', route: 'Topical', timing: 'Skincare routine', food: 'N/A', duration: 'Ongoing', range: 'Per formulation', notes: 'Commonly combined with Pal-Tetrapeptide-7 (as "Matrixyl 3000").' },
      sideEffects: ['Rare mild irritation'],
      warnings: ['Topical use only', 'Not medical advice'],
    },
    {
      slug: 'palmitoyl-tetrapeptide-7', name: 'Palmitoyl Tetrapeptide-7', category: 'skin', phase: 'Phase 2',
      overview: 'Anti-inflammatory lipopeptide that helps reduce skin "inflammaging."',
      mechanism: 'Reduces excess production of inflammatory cytokines (e.g. IL-6) triggered by UV and stress, protecting the dermal matrix from inflammation-driven aging.',
      benefits: ['Calms inflammation-driven aging', 'Protects collagen from breakdown', 'Improves resilience and tone'],
      dosing: { dose: 'Topical (trace %)', frequency: 'Daily', route: 'Topical', timing: 'Skincare routine', food: 'N/A', duration: 'Ongoing', range: 'Per formulation', notes: 'Pairs with Pal-Tripeptide-1 in popular serums.' },
      sideEffects: ['Rare mild irritation'],
      warnings: ['Topical use only', 'Not medical advice'],
    },
    {
      slug: 'acetyl-hexapeptide-3', name: 'Acetyl Hexapeptide-3', category: 'skin', phase: 'Phase 2', aka: ['Acetyl Hexapeptide-8'],
      overview: 'Neuromuscular-targeting topical peptide for reducing expression lines.',
      mechanism: 'Same SNARE-modulating mechanism as Argireline (the names are often used interchangeably), gently limiting expression-line muscle contraction.',
      benefits: ['Softens dynamic wrinkles', 'Topical, reversible, well tolerated'],
      dosing: { dose: 'Topical 5–10%', frequency: 'Daily (AM/PM)', route: 'Topical serum', timing: 'Skincare routine', food: 'N/A', duration: 'Ongoing', range: '5–10% in formulation', notes: 'Effects build gradually over several weeks.' },
      sideEffects: ['Rare irritation'],
      warnings: ['Topical use only', 'Not medical advice'],
    },
    {
      slug: 'myristoyl-pentapeptide-17', name: 'Myristoyl Pentapeptide-17', category: 'skin', phase: 'Preclinical',
      overview: 'Peptide that stimulates keratin production, researched for hair and lash growth.',
      mechanism: 'Upregulates keratin gene expression in follicle cells, aiming to lengthen and thicken lashes and brows.',
      benefits: ['Promotes lash/brow fullness', 'Common in eyelash serums'],
      dosing: { dose: 'Topical (trace %)', frequency: 'Daily', route: 'Topical (lash/brow line)', timing: 'PM', food: 'N/A', duration: 'Ongoing', range: 'Per formulation', notes: 'Cosmetic lash-serum ingredient.' },
      sideEffects: ['Eye-area irritation if misapplied'],
      warnings: ['Avoid direct eye contact', 'Not medical advice'],
    },
    {
      slug: 'biotinoyl-tripeptide-1', name: 'Biotinoyl Tripeptide-1', category: 'skin', phase: 'Preclinical',
      overview: 'Biotin–peptide conjugate studied for strengthening hair-follicle anchoring.',
      mechanism: 'Couples biotin to a signaling tripeptide to support follicle-anchoring proteins and improve hair-shaft resilience.',
      benefits: ['Supports hair anchoring/strength', 'Used in anti-thinning hair products'],
      dosing: { dose: 'Topical (trace %)', frequency: 'Daily', route: 'Topical scalp', timing: 'Any', food: 'N/A', duration: 'Ongoing', range: 'Per formulation', notes: 'Cosmetic scalp-serum ingredient.' },
      sideEffects: ['Rare scalp irritation'],
      warnings: ['Topical use only', 'Not medical advice'],
    },

    /* ─── GROWTH HORMONE ─────────────────────────────────────────────────── */
    {
      slug: 'ipamorelin', name: 'Ipamorelin', category: 'growth_hormone', phase: 'Phase 2',
      overview: 'Selective growth-hormone secretagogue, considered one of the cleanest and best-tolerated GHRPs.',
      mechanism: 'Selective ghrelin/GH-secretagogue receptor agonist that triggers a pulse of growth hormone from the pituitary with minimal effect on cortisol or prolactin.',
      benefits: ['Stimulates a natural GH pulse', 'Minimal cortisol/prolactin impact vs older GHRPs', 'May support recovery, body composition, and sleep', 'Little appetite stimulation'],
      dosing: { dose: '200–300 mcg', frequency: '1–3× daily', route: 'Subcutaneous injection', timing: 'Before bed and/or post-workout, on empty stomach', food: 'Fasted (no food 30 min around dose)', duration: '8–12 week cycles', range: '200–900 mcg/day', notes: 'Commonly paired with CJC-1295 / Mod GRF (1-29) for synergistic GH release.' },
      sideEffects: ['Injection-site reactions', 'Head-rush / flushing', 'Water retention', 'Tingling'],
      warnings: ['Caution with diabetes/insulin resistance', 'WADA-prohibited in sport', 'Not medical advice'],
    },
    {
      slug: 'cjc-1295', name: 'CJC-1295', category: 'growth_hormone', phase: 'Phase 2', aka: ['Modified GRF (1-29) analog'],
      overview: 'Synthetic GHRH analog that stimulates growth-hormone release from the pituitary.',
      mechanism: 'Mimics growth-hormone-releasing hormone (GHRH), increasing the amplitude of natural GH pulses. Usually combined with a GHRP for synergy.',
      benefits: ['Increases GH and IGF-1 output', 'Supports recovery and body composition', 'Synergistic with ghrelin-receptor agonists (GHRPs)'],
      dosing: { dose: '100 mcg', frequency: '1–2× daily', route: 'Subcutaneous injection', timing: 'Before bed / post-workout, fasted', food: 'Fasted', duration: '8–12 week cycles', range: '100–200 mcg/day', notes: 'The non-DAC version clears quickly and is typically dosed with Ipamorelin.' },
      sideEffects: ['Injection-site reactions', 'Flushing', 'Water retention', 'Transient headache'],
      warnings: ['Caution with diabetes', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'cjc-1295-dac', name: 'CJC-1295 DAC', category: 'growth_hormone', phase: 'Phase 2',
      overview: 'Long-acting CJC-1295 with a Drug Affinity Complex that extends half-life to several days via albumin binding.',
      mechanism: 'GHRH analog modified with a DAC group that binds serum albumin, sustaining GHRH activity for days and creating a continuous "GH bleed" rather than discrete pulses.',
      benefits: ['Once-weekly convenience', 'Sustained elevation of GH/IGF-1'],
      dosing: { dose: '1–2 mg', frequency: 'Once weekly', route: 'Subcutaneous injection', timing: 'Any', food: 'With or without', duration: '8–12 weeks', range: '1–2 mg/week', notes: 'Continuous elevation may blunt natural pulsatility; many prefer non-DAC for a more physiologic pattern.' },
      sideEffects: ['Water retention', 'Tingling/numbness', 'Injection-site reactions', 'Headache'],
      warnings: ['Caution with diabetes', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'tesamorelin', name: 'Tesamorelin', category: 'growth_hormone', phase: 'FDA Approved',
      overview: 'FDA-approved GHRH analog indicated for reducing visceral fat in HIV-associated lipodystrophy.',
      status: 'FDA-approved (Egrifta) for HIV-associated lipodystrophy.',
      mechanism: 'Stabilized GHRH analog that raises GH and IGF-1, preferentially reducing visceral adipose tissue.',
      benefits: ['Reduces visceral (belly) fat in studies', 'Raises GH/IGF-1', 'May improve some cognitive markers in research'],
      dosing: { dose: '2 mg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Any', food: 'With or without', duration: 'Per prescriber', range: '2 mg/day', notes: 'Prescription medication; use under medical supervision.' },
      sideEffects: ['Injection-site reactions', 'Joint pain', 'Swelling', 'Raised blood glucose'],
      warnings: ['Avoid with active malignancy', 'Caution with diabetes', 'Prescription only', 'Not medical advice'],
    },
    {
      slug: 'sermorelin', name: 'Sermorelin', category: 'growth_hormone', phase: 'FDA Approved',
      overview: 'Truncated GHRH (1-29) analog formerly FDA-approved for pediatric GH deficiency; used in anti-aging GH protocols.',
      status: 'Previously FDA-approved; original product discontinued but compounded versions are prescribed.',
      mechanism: 'Shortest active GHRH fragment; stimulates the pituitary to release GH in a natural, pulsatile pattern, mainly overnight.',
      benefits: ['Promotes natural nighttime GH pulse', 'Supports recovery, sleep, and body composition'],
      dosing: { dose: '100–300 mcg', frequency: 'Nightly', route: 'Subcutaneous injection', timing: 'Before bed, fasted', food: 'Fasted', duration: 'Ongoing per prescriber', range: '100–500 mcg/day', notes: 'Shorter-acting GHRH; often compounded with a GHRP.' },
      sideEffects: ['Injection-site reactions', 'Flushing', 'Headache'],
      warnings: ['Caution with diabetes', 'Prescription/compounded', 'Not medical advice'],
    },
    {
      slug: 'ghrp-6', name: 'GHRP-6', category: 'growth_hormone', phase: 'Preclinical',
      overview: 'First-generation GH secretagogue producing strong GH release with significant appetite stimulation.',
      mechanism: 'Ghrelin-receptor agonist that strongly stimulates GH release; also markedly increases hunger and can raise cortisol/prolactin at higher doses.',
      benefits: ['Strong GH pulse', 'Appetite stimulation (useful for bulking/underweight)'],
      dosing: { dose: '100–200 mcg', frequency: '2–3× daily', route: 'Subcutaneous injection', timing: 'Fasted, AM / post-workout / bed', food: 'Fasted', duration: '8–12 weeks', range: '100–600 mcg/day', notes: 'Often paired with a GHRH like Mod GRF (1-29).' },
      sideEffects: ['Strong hunger', 'Water retention', 'Tingling', 'Cortisol/prolactin rise at higher doses'],
      warnings: ['Caution with diabetes', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'ghrp-2', name: 'GHRP-2', category: 'growth_hormone', phase: 'Preclinical',
      overview: 'Potent GH-releasing peptide with strong GH output and less hunger than GHRP-6.',
      mechanism: 'Ghrelin-receptor agonist with potent GH-releasing action and somewhat less appetite stimulation than GHRP-6, though still some cortisol/prolactin effect.',
      benefits: ['Potent GH release', 'Less hunger than GHRP-6'],
      dosing: { dose: '100–200 mcg', frequency: '2–3× daily', route: 'Subcutaneous injection', timing: 'Fasted, AM / post-workout / bed', food: 'Fasted', duration: '8–12 weeks', range: '100–600 mcg/day', notes: 'Synergistic with GHRH analogs.' },
      sideEffects: ['Hunger', 'Water retention', 'Flushing', 'Mild prolactin/cortisol rise'],
      warnings: ['Caution with diabetes', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'hexarelin', name: 'Hexarelin', category: 'growth_hormone', phase: 'Phase 2',
      overview: 'Potent GHRP with unique cardioprotective properties via CD36 receptor binding.',
      mechanism: 'Strong ghrelin-receptor agonist; also binds the CD36 receptor, giving it researched cardioprotective effects independent of GH. GH response can desensitize with continuous use.',
      benefits: ['Potent GH release', 'Researched cardioprotective effects', 'Studied for heart-tissue protection'],
      dosing: { dose: '100 mcg', frequency: '1–2× daily', route: 'Subcutaneous injection', timing: 'Fasted', food: 'Fasted', duration: '4–8 weeks (cycled)', range: '100–200 mcg/day', notes: 'Prone to receptor desensitization — usually cycled or pulsed.' },
      sideEffects: ['Water retention', 'Prolactin/cortisol rise', 'Tingling'],
      warnings: ['Caution with diabetes', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'mk-677', name: 'MK-677', category: 'growth_hormone', phase: 'Phase 2', aka: ['Ibutamoren'],
      overview: 'Orally active GH secretagogue (not technically a peptide) that elevates GH and IGF-1 for ~24 hours.',
      mechanism: 'Non-peptide ghrelin-receptor agonist providing sustained, once-daily oral GH stimulation.',
      benefits: ['24-hour GH/IGF-1 elevation from an oral dose', 'Supports appetite, sleep depth, and recovery'],
      dosing: { dose: '10–25 mg', frequency: 'Once daily', route: 'Oral', timing: 'Before bed', food: 'With or without', duration: '8–16 weeks', range: '10–25 mg/day', notes: 'Can increase appetite, water retention, and fasting glucose.' },
      sideEffects: ['Increased appetite', 'Water retention / puffiness', 'Lethargy', 'Raised fasting glucose'],
      warnings: ['Caution with diabetes/insulin resistance', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'mod-grf-1-29', name: 'Modified GRF (1-29)', category: 'growth_hormone', phase: 'Phase 2', aka: ['CJC-1295 without DAC', 'Sermorelin analog'],
      overview: 'Stabilized GHRH fragment commonly paired with GHRPs for synergistic GH release.',
      mechanism: 'A tetra-substituted GHRH(1-29) fragment resistant to enzyme breakdown, producing a clean, short GH pulse that synergizes with ghrelin-receptor agonists.',
      benefits: ['Clean, pulsatile GH release', 'Strong synergy with Ipamorelin/GHRP', 'Short half-life mimics physiology'],
      dosing: { dose: '100 mcg', frequency: '1–3× daily', route: 'Subcutaneous injection', timing: 'Fasted, with a GHRP', food: 'Fasted', duration: '8–12 weeks', range: '100–300 mcg/day', notes: 'Classic stack: 100 mcg Mod GRF + 100 mcg Ipamorelin per dose.' },
      sideEffects: ['Flushing', 'Water retention', 'Injection-site reactions'],
      warnings: ['Caution with diabetes', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'fragment-176-191', name: 'Fragment 176-191', category: 'growth_hormone', phase: 'Preclinical', aka: ['HGH Frag 176-191', 'AOD analog'],
      overview: 'Fat-burning fragment of HGH studied for lipolysis without the anabolic or blood-sugar effects of full HGH.',
      mechanism: 'Corresponds to the C-terminal fat-metabolizing region of growth hormone; promotes lipolysis and fat oxidation without significantly affecting IGF-1 or blood glucose.',
      benefits: ['Targets fat metabolism', 'Minimal effect on IGF-1/blood sugar', 'Does not stimulate growth/anabolism'],
      dosing: { dose: '250–500 mcg', frequency: '1–2× daily', route: 'Subcutaneous injection', timing: 'Fasted / pre-cardio', food: 'Fasted', duration: '4–12 weeks', range: '250–1,000 mcg/day', notes: 'Often dosed fasted before cardio.' },
      sideEffects: ['Injection-site reactions', 'Transient fatigue'],
      warnings: ['Preclinical', 'Not medical advice'],
    },
    {
      slug: 'ghrp-1', name: 'GHRP-1', category: 'growth_hormone', phase: 'Preclinical',
      overview: 'Early-generation growth-hormone-releasing peptide with moderate GH stimulation.',
      mechanism: 'First-generation ghrelin-receptor agonist that triggers GH release; less commonly used than GHRP-2/6 or Ipamorelin.',
      benefits: ['Moderate GH release', 'Synergizes with GHRH analogs'],
      dosing: { dose: '100 mcg', frequency: '2–3× daily', route: 'Subcutaneous injection', timing: 'Fasted', food: 'Fasted', duration: '8–12 weeks', range: '100–300 mcg/day', notes: 'Largely superseded by newer, more selective GHRPs.' },
      sideEffects: ['Hunger', 'Water retention', 'Flushing'],
      warnings: ['Caution with diabetes', 'WADA-prohibited', 'Not medical advice'],
    },
    {
      slug: 'alexamorelin', name: 'Alexamorelin', category: 'growth_hormone', phase: 'Preclinical',
      overview: 'Synthetic GH-secretagogue pentapeptide; discontinued from clinical development.',
      mechanism: 'Ghrelin-receptor agonist that stimulates GH release; explored as a diagnostic/therapeutic agent but development was halted.',
      benefits: ['Stimulates GH release (research)'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: '—', range: 'No standard protocol', notes: 'Largely of historical/research interest; no established human dosing.' },
      sideEffects: ['Limited data'],
      warnings: ['Discontinued — minimal data', 'Not medical advice'],
    },
    {
      slug: 'macimorelin', name: 'Macimorelin', category: 'growth_hormone', phase: 'FDA Approved', aka: ['Macrilen'],
      overview: 'FDA-approved oral GH secretagogue used as a diagnostic test for adult GH deficiency.',
      status: 'FDA-approved (Macrilen) as a diagnostic agent.',
      mechanism: 'Oral ghrelin-receptor agonist that provokes a measurable GH response, used to diagnose adult growth-hormone deficiency.',
      benefits: ['Reliable oral GH-stimulation test', 'Avoids older provocative testing methods'],
      dosing: { dose: '0.5 mg/kg', frequency: 'Single test dose', route: 'Oral solution', timing: 'Fasted, in clinic', food: 'Fasted', duration: 'One-time diagnostic', range: '0.5 mg/kg', notes: 'Administered in a clinical setting as a diagnostic; not for ongoing use.' },
      sideEffects: ['Dysgeusia (taste change)', 'Dizziness', 'Headache', 'QT-interval prolongation'],
      warnings: ['Avoid drugs that prolong QT', 'Diagnostic use under medical supervision', 'Not medical advice'],
    },
    {
      slug: 'tabimorelin', name: 'Tabimorelin', category: 'growth_hormone', phase: 'Phase 2',
      overview: 'Oral non-peptide GH secretagogue; development discontinued after Phase 2.',
      mechanism: 'Orally active ghrelin-receptor agonist that raised GH/IGF-1 but showed metabolic and enzyme-induction issues, ending development.',
      benefits: ['Oral GH elevation (research)'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Oral (research)', timing: '—', food: '—', duration: '—', range: 'No standard protocol', notes: 'Development discontinued; of research interest only.' },
      sideEffects: ['Increased appetite', 'Metabolic/liver-enzyme effects in trials'],
      warnings: ['Discontinued', 'Not medical advice'],
    },
    {
      slug: 'pralmorelin', name: 'Pralmorelin', category: 'growth_hormone', phase: 'Phase 2', aka: ['GHRP-2 (diagnostic)'],
      overview: 'GHRP-2 approved in Japan as a diagnostic agent for growth-hormone deficiency.',
      status: 'Approved in Japan as a diagnostic; not FDA-approved.',
      mechanism: 'Ghrelin-receptor agonist (the diagnostic formulation of GHRP-2) used to provoke and measure GH release.',
      benefits: ['GH-stimulation diagnostic', 'Potent, rapid GH response'],
      dosing: { dose: '100 mcg (test)', frequency: 'Single test dose', route: 'Intravenous (diagnostic)', timing: 'In clinic', food: 'Fasted', duration: 'One-time diagnostic', range: 'Per protocol', notes: 'Diagnostic use; same molecule as GHRP-2.' },
      sideEffects: ['Flushing', 'Transient hunger'],
      warnings: ['Diagnostic use', 'Not medical advice'],
    },

    /* ─── WEIGHT LOSS ────────────────────────────────────────────────────── */
    {
      slug: 'semaglutide', name: 'Semaglutide', category: 'weight_loss', phase: 'FDA Approved', aka: ['Ozempic', 'Wegovy', 'Rybelsus'],
      overview: 'GLP-1 receptor agonist, FDA-approved for type-2 diabetes and chronic weight management.',
      status: 'FDA-approved. Large Phase 3 trials show ~15% mean body-weight reduction at higher doses.',
      mechanism: 'Mimics the incretin hormone GLP-1: suppresses appetite, slows gastric emptying, and improves insulin secretion and sensitivity.',
      benefits: ['Significant appetite suppression and weight loss', 'Improved glycemic control', 'Cardiovascular risk reduction in trials'],
      dosing: { dose: 'Titrated 0.25 → 2.4 mg', frequency: 'Once weekly', route: 'Subcutaneous injection', timing: 'Same day each week', food: 'With or without', duration: 'Ongoing per prescriber', range: '0.25–2.4 mg/week', notes: 'Dose is escalated slowly to limit GI side effects. Prescription medication.' },
      sideEffects: ['Nausea', 'Constipation / diarrhea', 'Reduced appetite', 'Injection-site reactions'],
      warnings: ['Boxed warning: thyroid C-cell tumor risk (rodents)', 'Avoid with personal/family history of medullary thyroid carcinoma or MEN-2', 'Pancreatitis caution', 'Not medical advice'],
    },
    {
      slug: 'tirzepatide', name: 'Tirzepatide', category: 'weight_loss', phase: 'FDA Approved', aka: ['Mounjaro', 'Zepbound'],
      overview: 'Dual GLP-1 / GIP receptor agonist, FDA-approved for type-2 diabetes and weight management.',
      status: 'FDA-approved. Phase 3 trials report ~20–22% mean weight loss at top dose.',
      mechanism: 'Activates both GIP and GLP-1 receptors for stronger appetite suppression and metabolic benefit than GLP-1 alone.',
      benefits: ['Greater weight loss than single-agonist GLP-1s in trials', 'Strong glycemic control', 'Appetite and craving reduction'],
      dosing: { dose: 'Titrated 2.5 → 15 mg', frequency: 'Once weekly', route: 'Subcutaneous injection', timing: 'Same day each week', food: 'With or without', duration: 'Ongoing per prescriber', range: '2.5–15 mg/week', notes: 'Escalated monthly to manage GI tolerance. Prescription medication.' },
      sideEffects: ['Nausea', 'Diarrhea / constipation', 'Decreased appetite', 'Injection-site reactions'],
      warnings: ['Boxed warning: thyroid C-cell tumor risk (rodents)', 'Avoid with MTC/MEN-2 history', 'Pancreatitis caution', 'Not medical advice'],
    },
    {
      slug: 'retatrutide', name: 'Retatrutide', category: 'weight_loss', phase: 'Phase 3',
      overview: 'Triple receptor agonist (GLP-1 / GIP / glucagon) — the most potent weight-loss peptide currently in trials.',
      status: 'Phase 3 (TRIUMPH program). Phase 2 showed ~24% mean weight loss at 48 weeks. Not FDA-approved.',
      mechanism: 'Adds glucagon-receptor activity to dual incretin action, boosting energy expenditure alongside appetite suppression.',
      benefits: ['Largest weight loss reported among incretin agents in trials', 'Improves glycemic and metabolic markers', 'May benefit fatty-liver disease'],
      dosing: { dose: 'Titrated (trial)', frequency: 'Once weekly', route: 'Subcutaneous injection', timing: 'Same day each week', food: 'With or without', duration: 'Investigational', range: 'Trial doses up to 12 mg/week', notes: 'Investigational — no approved dosing. Trial doses are titrated slowly.' },
      sideEffects: ['Nausea', 'GI upset', 'Appetite loss', 'Increased heart rate'],
      warnings: ['Investigational — not FDA-approved', 'Not medical advice'],
    },
    {
      slug: 'aod-9604', name: 'AOD-9604', category: 'weight_loss', phase: 'Phase 2',
      overview: 'Modified HGH fragment researched for fat metabolism without the typical HGH side-effect profile.',
      mechanism: 'A modified form of the GH fat-burning fragment (176-191) that stimulates lipolysis and inhibits lipogenesis without affecting IGF-1 or blood glucose.',
      benefits: ['Promotes fat breakdown', 'Does not raise IGF-1 or blood sugar', 'Studied for cartilage/joint support'],
      dosing: { dose: '300 mcg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Fasted, morning', food: 'Fasted', duration: '8–12 weeks', range: '250–500 mcg/day', notes: 'Does not significantly affect IGF-1 or blood sugar in studies.' },
      sideEffects: ['Injection-site reactions', 'Generally well tolerated'],
      warnings: ['Preclinical/early human data', 'Not medical advice'],
    },
    {
      slug: 'liraglutide', name: 'Liraglutide', category: 'weight_loss', phase: 'FDA Approved', aka: ['Saxenda', 'Victoza'],
      overview: 'Daily GLP-1 agonist, FDA-approved for both diabetes and weight management.',
      status: 'FDA-approved.',
      mechanism: 'GLP-1 receptor agonist that suppresses appetite, slows gastric emptying, and improves glucose control; shorter-acting than weekly agents (daily dosing).',
      benefits: ['Appetite suppression and weight loss', 'Glycemic control', 'Established cardiovascular data'],
      dosing: { dose: 'Titrated 0.6 → 3.0 mg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Same time daily', food: 'With or without', duration: 'Ongoing per prescriber', range: '0.6–3.0 mg/day', notes: 'Prescription medication; titrated weekly.' },
      sideEffects: ['Nausea', 'Diarrhea', 'Reduced appetite', 'Injection-site reactions'],
      warnings: ['Boxed warning: thyroid C-cell tumor risk (rodents)', 'Avoid with MTC/MEN-2 history', 'Pancreatitis caution', 'Not medical advice'],
    },
    {
      slug: 'exenatide', name: 'Exenatide', category: 'weight_loss', phase: 'FDA Approved', aka: ['Byetta', 'Bydureon'],
      overview: 'The first GLP-1 agonist, derived from Gila-monster venom; FDA-approved for type-2 diabetes.',
      status: 'FDA-approved.',
      mechanism: 'Synthetic exendin-4 (from Gila-monster venom) that activates GLP-1 receptors to improve glucose control and reduce appetite.',
      benefits: ['Glycemic control', 'Modest weight loss', 'Available in twice-daily and weekly forms'],
      dosing: { dose: '5–10 mcg (Byetta) / 2 mg (Bydureon)', frequency: 'Twice daily or once weekly', route: 'Subcutaneous injection', timing: 'Before meals (Byetta)', food: 'Before meals', duration: 'Ongoing per prescriber', range: 'Per formulation', notes: 'Prescription medication.' },
      sideEffects: ['Nausea', 'Injection-site nodules (weekly form)', 'Diarrhea'],
      warnings: ['Avoid with severe kidney impairment', 'Pancreatitis caution', 'Not medical advice'],
    },
    {
      slug: 'dulaglutide', name: 'Dulaglutide', category: 'weight_loss', phase: 'FDA Approved', aka: ['Trulicity'],
      overview: 'Weekly GLP-1 agonist, FDA-approved for type-2 diabetes with cardiovascular risk reduction.',
      status: 'FDA-approved.',
      mechanism: 'Long-acting GLP-1 receptor agonist fused to an antibody fragment for once-weekly dosing.',
      benefits: ['Glycemic control', 'Cardiovascular risk reduction', 'Modest weight loss'],
      dosing: { dose: '0.75 → 4.5 mg', frequency: 'Once weekly', route: 'Subcutaneous injection', timing: 'Same day weekly', food: 'With or without', duration: 'Ongoing per prescriber', range: '0.75–4.5 mg/week', notes: 'Prescription medication.' },
      sideEffects: ['Nausea', 'Diarrhea', 'Reduced appetite'],
      warnings: ['Boxed warning: thyroid C-cell tumor risk (rodents)', 'Avoid with MTC/MEN-2 history', 'Not medical advice'],
    },
    {
      slug: 'lixisenatide', name: 'Lixisenatide', category: 'weight_loss', phase: 'FDA Approved', aka: ['Adlyxin'],
      overview: 'Short-acting GLP-1 agonist focused on controlling post-meal glucose spikes.',
      status: 'FDA-approved.',
      mechanism: 'Short-acting GLP-1 receptor agonist that strongly slows gastric emptying, blunting after-meal glucose rises.',
      benefits: ['Lowers post-prandial glucose', 'Modest weight effect'],
      dosing: { dose: '10 → 20 mcg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Within 1 hr before first meal', food: 'Before meal', duration: 'Ongoing per prescriber', range: '10–20 mcg/day', notes: 'Prescription medication.' },
      sideEffects: ['Nausea', 'Vomiting', 'Headache'],
      warnings: ['Pancreatitis caution', 'Not medical advice'],
    },
    {
      slug: 'survodutide', name: 'Survodutide', category: 'weight_loss', phase: 'Phase 3',
      overview: 'Dual GLP-1 / glucagon agonist in late-stage trials for obesity and liver disease.',
      status: 'Phase 3. Not FDA-approved.',
      mechanism: 'Activates GLP-1 and glucagon receptors to combine appetite suppression with increased energy expenditure; studied heavily for fatty-liver disease (MASH).',
      benefits: ['Significant weight loss in trials', 'Promising data for fatty-liver disease'],
      dosing: { dose: 'Titrated (trial)', frequency: 'Once weekly', route: 'Subcutaneous injection', timing: 'Weekly', food: 'With or without', duration: 'Investigational', range: 'Trial doses', notes: 'Investigational — no approved dosing.' },
      sideEffects: ['Nausea', 'Vomiting', 'GI upset'],
      warnings: ['Investigational', 'Not medical advice'],
    },

    /* ─── COGNITIVE ──────────────────────────────────────────────────────── */
    {
      slug: 'selank', name: 'Selank', category: 'cognitive', phase: 'Phase 2',
      overview: 'Anxiolytic peptide approved in Russia; non-sedative and non-addictive.',
      mechanism: 'Synthetic analog of the immunomodulatory peptide tuftsin; modulates GABA, serotonin, and BDNF pathways and stabilizes enkephalins.',
      benefits: ['Reduces anxiety without sedation', 'May improve focus and mental clarity', 'Non-addictive profile'],
      dosing: { dose: '250–500 mcg', frequency: '1–3× daily', route: 'Intranasal', timing: 'Spread through day', food: 'Any', duration: '2–4 week courses', range: '250–900 mcg/day', notes: 'Commonly used intranasally; approved as a medicine in Russia only.' },
      sideEffects: ['Nasal irritation', 'Mild fatigue', 'Rare headache'],
      warnings: ['Not approved in the US', 'Not medical advice'],
    },
    {
      slug: 'semax', name: 'Semax', category: 'cognitive', phase: 'Phase 2',
      overview: 'Nootropic peptide approved in Russia that supports focus, memory, and neuroplasticity.',
      mechanism: 'ACTH(4-10) analog that raises BDNF and NGF, modulates dopamine/serotonin, and is studied for neuroprotection.',
      benefits: ['May enhance focus and memory', 'Raises BDNF/NGF in studies', 'Researched for stroke recovery (in Russia)'],
      dosing: { dose: '250–600 mcg', frequency: '1–2× daily', route: 'Intranasal', timing: 'Morning / midday', food: 'Any', duration: '10–14 day courses', range: '250–1,200 mcg/day', notes: 'Approved as a medicine in Russia only.' },
      sideEffects: ['Nasal irritation', 'Overstimulation at high doses'],
      warnings: ['Not approved in the US', 'Not medical advice'],
    },
    {
      slug: 'dihexa', name: 'Dihexa', category: 'cognitive', phase: 'Preclinical',
      overview: 'Potent experimental nootropic that promotes synapse formation in animal models. No human trials.',
      mechanism: 'Angiotensin-IV-derived peptide that augments hepatocyte growth factor (HGF)/c-Met signaling to promote new synapse formation in research models.',
      benefits: ['Promotes synaptogenesis (animal data)', 'Studied for memory/neurodegeneration'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Oral/transdermal (research)', timing: '—', food: '—', duration: '—', range: 'No human protocol', notes: 'No human trials; potency raises unknown long-term-safety concerns.' },
      sideEffects: ['Unknown in humans'],
      warnings: ['No human safety data', 'Theoretical growth-signaling concern', 'Not medical advice'],
    },
    {
      slug: 'noopept', name: 'Noopept', category: 'cognitive', phase: 'Phase 2',
      overview: 'Dipeptide-derived nootropic studied for memory and neuroprotection; approved in Russia.',
      mechanism: 'A proline-containing dipeptide that raises BDNF/NGF and modulates glutamate (AMPA/NMDA) signaling; structurally related to racetam nootropics but far more potent by weight.',
      benefits: ['May support memory and learning', 'Neuroprotective in studies', 'Mild anxiolytic effect'],
      dosing: { dose: '10–30 mg', frequency: '1–3× daily', route: 'Oral or sublingual', timing: 'With meals', food: 'With food', duration: '4–8 week courses', range: '10–30 mg/day', notes: 'Approved as a medicine in Russia; sold as a supplement elsewhere.' },
      sideEffects: ['Headache (often from underdosing choline)', 'Irritability', 'Fatigue'],
      warnings: ['Not approved in the US', 'Not medical advice'],
    },
    {
      slug: 'p21', name: 'P21', category: 'cognitive', phase: 'Preclinical',
      overview: 'Neurogenic peptide that promotes hippocampal neurogenesis in research models.',
      mechanism: 'A peptidergic compound that mimics ciliary neurotrophic factor (CNTF) activity, promoting the birth of new neurons in the hippocampus in animal studies.',
      benefits: ['Promotes hippocampal neurogenesis (animal data)', 'Studied for memory and neurodegeneration'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Subcutaneous/intranasal (research)', timing: '—', food: '—', duration: '—', range: 'No human protocol', notes: 'Preclinical only; no validated human dosing.' },
      sideEffects: ['Unknown in humans'],
      warnings: ['No human data', 'Not medical advice'],
    },
    {
      slug: 'fgl', name: 'FGL', category: 'cognitive', phase: 'Preclinical', aka: ['FG Loop peptide'],
      overview: 'NCAM-derived peptide that promotes synaptic plasticity and memory formation in studies.',
      mechanism: 'Derived from the neural cell adhesion molecule (NCAM); activates FGF receptors to support synaptic plasticity and has shown anti-inflammatory/neuroprotective effects in animals.',
      benefits: ['Supports synaptic plasticity (animal data)', 'Studied for memory and neuroprotection'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Subcutaneous/intranasal (research)', timing: '—', food: '—', duration: '—', range: 'No human protocol', notes: 'Preclinical research peptide.' },
      sideEffects: ['Unknown in humans'],
      warnings: ['No human data', 'Not medical advice'],
    },
    {
      slug: 'cortagen', name: 'Cortagen', category: 'cognitive', phase: 'Preclinical',
      overview: 'Bioregulatory tetrapeptide studied for cerebral-cortex function.',
      mechanism: 'A short "bioregulator" peptide (Khavinson peptides) proposed to influence gene expression supporting cortical neuron repair and function.',
      benefits: ['Studied for nerve repair and cortical function', 'Part of the Russian bioregulator peptide family'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Daytime', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Used in Russian bioregulator protocols; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'pinealon', name: 'Pinealon', category: 'cognitive', phase: 'Preclinical',
      overview: 'Bioregulatory tripeptide targeting pineal-gland and CNS function.',
      mechanism: 'A short bioregulator peptide proposed to support neuron protection and circadian/CNS regulation via gene-expression effects.',
      benefits: ['Studied for neuroprotection and sleep/circadian support'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Daytime', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Russian bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'epitalon-cognitive', name: 'Epitalon (Cognitive)', category: 'cognitive', phase: 'Preclinical', aka: ['Epithalon'],
      overview: 'Epitalon applied for cognitive and sleep-architecture benefits via pineal regulation.',
      mechanism: 'Pineal tetrapeptide that helps normalize melatonin and circadian rhythm, which may secondarily support sleep quality and cognitive function.',
      benefits: ['May improve sleep architecture', 'Circadian-rhythm support', 'Antioxidant activity'],
      dosing: { dose: '5–10 mg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Evening', food: 'Any', duration: '10–20 day courses', range: '5–10 mg/day in courses', notes: 'Same molecule as Epithalon; here framed for sleep/cognition.' },
      sideEffects: ['Injection-site reactions', 'Generally well tolerated'],
      warnings: ['Human evidence limited', 'Not medical advice'],
    },
    {
      slug: 'bpc-157-cognitive', name: 'BPC-157 (Cognitive)', category: 'cognitive', phase: 'Preclinical', aka: ['Body Protection Compound 157'],
      overview: 'BPC-157 studied for neuroprotective and dopamine-modulating cognitive support.',
      mechanism: 'Beyond tissue healing, BPC-157 interacts with the dopaminergic and serotonergic systems and the gut–brain axis, with animal studies suggesting neuroprotective effects.',
      benefits: ['Studied for neuroprotection (animal models)', 'May modulate mood via dopamine/gut–brain axis'],
      dosing: { dose: '250–500 mcg', frequency: '1–2× daily', route: 'Subcutaneous or oral', timing: 'Morning / evening', food: 'With or without', duration: '4–12 weeks', range: '250–1,000 mcg/day', notes: 'Same compound as healing-category BPC-157, framed for neuro applications.' },
      sideEffects: ['Injection-site irritation', 'Nausea', 'Fatigue'],
      warnings: ['FDA Category 2 — restricted from compounding', 'Not medical advice'],
    },

    /* ─── IMMUNE ─────────────────────────────────────────────────────────── */
    {
      slug: 'll-37', name: 'LL-37', category: 'immune', phase: 'Phase 1', aka: ['Cathelicidin LL-37'],
      overview: 'Human antimicrobial peptide with broad-spectrum activity and wound-healing properties.',
      mechanism: 'Cationic host-defense peptide that disrupts microbial membranes and modulates innate immune signaling and wound repair.',
      benefits: ['Broad antimicrobial activity', 'Immune modulation', 'Wound-healing research'],
      dosing: { dose: '100–500 mcg', frequency: 'Daily (research)', route: 'Subcutaneous injection', timing: 'Any', food: 'Any', duration: 'Short courses', range: 'No established human protocol', notes: 'Can be pro-inflammatory at higher doses; early-stage research only.' },
      sideEffects: ['Injection-site irritation', 'Possible inflammatory response'],
      warnings: ['Early-stage research', 'Pro-inflammatory potential', 'Not medical advice'],
    },
    {
      slug: 'kpv', name: 'KPV', category: 'immune', phase: 'Preclinical', aka: ['Lys-Pro-Val'],
      overview: 'Anti-inflammatory C-terminal fragment of alpha-MSH that does not cause immunosuppression.',
      status: 'Preclinical; on the FDA July 2026 PCAC review agenda.',
      mechanism: 'Tripeptide fragment of α-MSH with intracellular anti-inflammatory action (NF-κB modulation); studied for gut and skin inflammation.',
      benefits: ['Anti-inflammatory without immunosuppression', 'Studied for IBD/gut and skin conditions', 'May aid healing of inflamed tissue'],
      dosing: { dose: '200–500 mcg', frequency: '1–2× daily', route: 'Subcutaneous or oral', timing: 'Any', food: 'Any', duration: '4–8 weeks', range: '200–1,000 mcg/day', notes: 'Often used in gut-healing protocols, sometimes with BPC-157.' },
      sideEffects: ['Generally well tolerated', 'Injection-site irritation'],
      warnings: ['Preclinical', 'Not medical advice'],
    },
    {
      slug: 'thymosin-alpha-1', name: 'Thymosin Alpha-1', category: 'immune', phase: 'Phase 3', aka: ['Tα1', 'Zadaxin'],
      overview: 'Thymic peptide for immune modulation; approved in 35+ countries.',
      status: 'Approved in many countries (e.g. for hepatitis, immune support). Not FDA-approved.',
      mechanism: 'Enhances T-cell maturation and function and modulates innate/adaptive immunity; used as an immune-restorative and vaccine adjuvant.',
      benefits: ['Supports T-cell-mediated immunity', 'Studied for chronic infections and as a vaccine adjuvant', 'Immune modulation in immunocompromised states'],
      dosing: { dose: '1.6 mg', frequency: '2× weekly', route: 'Subcutaneous injection', timing: 'Any', food: 'Any', duration: 'Per protocol', range: '1.6 mg doses', notes: 'Dosing varies by indication and prescriber.' },
      sideEffects: ['Injection-site reactions', 'Mild flu-like symptoms'],
      warnings: ['Not FDA-approved', 'Use under medical guidance', 'Not medical advice'],
    },
    {
      slug: 'vip', name: 'VIP', category: 'immune', phase: 'Phase 2', aka: ['Vasoactive Intestinal Peptide'],
      overview: 'Immunomodulatory peptide used in mold-illness (CIRS) protocols.',
      mechanism: 'A signaling neuropeptide that regulates immune balance, inflammation, and pulmonary/vascular function; used to restore regulatory function late in CIRS protocols.',
      benefits: ['Immune/inflammation modulation', 'Studied for CIRS and pulmonary hypertension', 'May improve quality-of-life markers in CIRS'],
      dosing: { dose: '50 mcg (1 spray)', frequency: '1–4× daily', route: 'Intranasal', timing: 'Spread through day', food: 'Any', duration: 'Per protocol', range: 'Per prescriber', notes: 'Typically used late in the Shoemaker CIRS protocol after other steps are corrected.' },
      sideEffects: ['Transient blood-pressure changes', 'Flushing', 'Nasal irritation'],
      warnings: ['Use under medical supervision', 'Not medical advice'],
    },
    {
      slug: 'thymulin', name: 'Thymulin', category: 'immune', phase: 'Preclinical',
      overview: 'Zinc-dependent thymic peptide that promotes T-cell maturation and immune balance.',
      mechanism: 'A thymic hormone that requires zinc to become active; supports T-cell differentiation and has anti-inflammatory and analgesic effects in studies.',
      benefits: ['Supports T-cell maturation', 'Anti-inflammatory activity', 'Zinc-dependent immune balance'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: '—', range: 'No standard human protocol', notes: 'Activity depends on adequate zinc status.' },
      sideEffects: ['Limited human data'],
      warnings: ['Preclinical', 'Not medical advice'],
    },
    {
      slug: 'thymopoietin', name: 'Thymopoietin', category: 'immune', phase: 'Preclinical',
      overview: 'Thymic polypeptide that drives T-cell differentiation from bone-marrow precursors.',
      mechanism: 'A thymic protein that guides the maturation of T-cells from precursor cells and influences neuromuscular transmission.',
      benefits: ['Supports T-cell development', 'Parent molecule of thymopentin'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: '—', range: 'No standard human protocol', notes: 'Active fragment (thymopentin) is more commonly used.' },
      sideEffects: ['Limited human data'],
      warnings: ['Preclinical', 'Not medical advice'],
    },
    {
      slug: 'thymopentin', name: 'Thymopentin', category: 'immune', phase: 'Phase 2',
      overview: 'Active pentapeptide fragment of thymopoietin used for immune regulation.',
      mechanism: 'The biologically active 5-residue fragment of thymopoietin; promotes T-cell maturation and has been used to support immune function in immunodeficiency and some autoimmune settings.',
      benefits: ['Supports T-cell function', 'Immune-modulating in research/clinical use abroad'],
      dosing: { dose: '~50 mg', frequency: '3× weekly', route: 'Subcutaneous/IV (clinical)', timing: 'Any', food: 'Any', duration: 'Per protocol', range: 'Clinical dosing varies', notes: 'Used clinically in some countries; not FDA-approved.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Not FDA-approved', 'Not medical advice'],
    },
    {
      slug: 'beta-defensin-2', name: 'Beta-Defensin-2', category: 'immune', phase: 'Preclinical',
      overview: 'Innate immune-defense peptide with antimicrobial and chemotactic properties.',
      mechanism: 'A host-defense peptide that disrupts microbial membranes and recruits immune cells to sites of infection.',
      benefits: ['Antimicrobial activity', 'Recruits immune cells (chemotaxis)'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Research', timing: '—', food: '—', duration: '—', range: 'No human protocol', notes: 'Primarily a research molecule.' },
      sideEffects: ['Unknown in humans'],
      warnings: ['Preclinical', 'Not medical advice'],
    },
    {
      slug: 'lactoferrin-peptide', name: 'Lactoferrin Peptide', category: 'immune', phase: 'Phase 2',
      overview: 'Bioactive peptide from milk protein with antimicrobial and immunomodulatory effects.',
      mechanism: 'Derived from lactoferrin; binds iron (limiting microbial growth), disrupts pathogen membranes, and modulates immune and gut-barrier function.',
      benefits: ['Antimicrobial/antiviral activity', 'Gut and immune support', 'Iron regulation'],
      dosing: { dose: '100–300 mg', frequency: 'Once daily', route: 'Oral', timing: 'Any', food: 'With or without', duration: 'Ongoing', range: '100–300 mg/day', notes: 'Lactoferrin is sold as an oral supplement.' },
      sideEffects: ['Mild GI upset'],
      warnings: ['Dairy-derived (allergen)', 'Not medical advice'],
    },
    {
      slug: 'cathelicidin', name: 'Cathelicidin', category: 'immune', phase: 'Preclinical',
      overview: 'Precursor antimicrobial peptide of the innate immune system (parent of LL-37).',
      mechanism: 'The precursor protein that is cleaved into active LL-37; central to innate antimicrobial defense and is upregulated by adequate vitamin D.',
      benefits: ['Source of antimicrobial LL-37', 'Innate immune defense'],
      dosing: { dose: 'N/A', frequency: '—', route: 'Endogenous', timing: '—', food: '—', duration: '—', range: 'Supported indirectly via vitamin D', notes: 'Generally supported indirectly (e.g. vitamin D status) rather than dosed directly.' },
      sideEffects: ['N/A'],
      warnings: ['Research context', 'Not medical advice'],
    },

    /* ─── ANTI-AGING & LONGEVITY ─────────────────────────────────────────── */
    {
      slug: 'epithalon', name: 'Epithalon', category: 'anti_aging', phase: 'Preclinical', aka: ['Epitalon', 'Epithalone'],
      overview: 'Tetrapeptide studied as a telomerase activator for anti-aging effects on cellular lifespan.',
      mechanism: 'Synthetic analog of the pineal peptide epithalamin; research suggests it can activate telomerase and help regulate melatonin/circadian rhythm.',
      benefits: ['Studied for telomere maintenance', 'May support sleep and circadian rhythm', 'Antioxidant activity in studies'],
      dosing: { dose: '5–10 mg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Evening', food: 'Any', duration: '10–20 day courses, 1–2×/year', range: '5–10 mg/day in courses', notes: 'Typically run as short intermittent courses rather than continuously.' },
      sideEffects: ['Injection-site reactions', 'Generally well tolerated in studies'],
      warnings: ['Human evidence limited', 'Not medical advice'],
    },
    {
      slug: 'mots-c', name: 'MOTS-c', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Mitochondrial-derived peptide studied for metabolic regulation and as an exercise mimetic.',
      mechanism: 'Mitochondrial-encoded peptide that activates AMPK and improves insulin sensitivity and metabolic flexibility.',
      benefits: ['May improve metabolic health and insulin sensitivity', 'Studied as an exercise-mimetic', 'Mitochondrial support'],
      dosing: { dose: '5–10 mg', frequency: '2–3× weekly', route: 'Subcutaneous injection', timing: 'Any', food: 'Any', duration: '4–8 weeks', range: '10–30 mg/week', notes: 'Protocols are anecdotal; no human dosing standard exists.' },
      sideEffects: ['Injection-site reactions', 'Fatigue'],
      warnings: ['Preclinical', 'Not medical advice'],
    },
    {
      slug: 'humanin', name: 'Humanin', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Mitochondrial-derived peptide with neuroprotective and metabolic effects in research.',
      mechanism: 'One of the first identified mitochondrial-derived peptides; protects cells from apoptosis and oxidative stress and improves insulin sensitivity in studies.',
      benefits: ['Neuroprotective in models', 'Cytoprotective/anti-apoptotic', 'Metabolic support'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: '—', range: 'No standard human protocol', notes: 'Preclinical; analogs being explored for neurodegeneration.' },
      sideEffects: ['Unknown in humans'],
      warnings: ['Preclinical', 'Not medical advice'],
    },
    {
      slug: 'ss-31', name: 'SS-31', category: 'anti_aging', phase: 'FDA Approved', aka: ['Elamipretide'],
      overview: 'Mitochondria-targeted peptide; an approved indication exists for the rare disorder Barth syndrome.',
      status: 'Approved for Barth syndrome; investigational for other mitochondrial conditions.',
      mechanism: 'Concentrates in the inner mitochondrial membrane, stabilizing cardiolipin to improve mitochondrial energy production and reduce oxidative damage.',
      benefits: ['Improves mitochondrial energy output', 'Studied for heart failure and mitochondrial disease', 'Reduces oxidative stress'],
      dosing: { dose: '~40 mg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Any', food: 'Any', duration: 'Per prescriber', range: 'Clinical dosing', notes: 'Approved for a rare disease; broader use is investigational.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Approved only for specific indication', 'Not medical advice'],
    },
    {
      slug: 'nad-precursors', name: 'NAD+ Precursors', category: 'anti_aging', phase: 'Phase 2', aka: ['NMN', 'NR'],
      overview: 'NAD+ boosters (NMN, NR) researched for cellular energy, DNA repair, and longevity pathways.',
      mechanism: 'Provide building blocks that raise cellular NAD+, a coenzyme central to mitochondrial energy, sirtuin activity, and DNA repair that declines with age.',
      benefits: ['Raises cellular NAD+', 'Supports mitochondrial energy and DNA repair', 'Studied for metabolic and vascular aging'],
      dosing: { dose: '250–1,000 mg', frequency: 'Once daily', route: 'Oral (or NAD+ IV/SubQ)', timing: 'Morning', food: 'With or without', duration: 'Ongoing', range: '250–1,000 mg/day', notes: 'Oral NMN/NR are sold as supplements; injectable NAD+ is used in some clinics.' },
      sideEffects: ['Flushing (NR)', 'Mild GI upset', 'Nausea with IV if infused fast'],
      warnings: ['Supplement-grade quality varies', 'Not medical advice'],
    },
    {
      slug: 'foxo4-dri', name: 'FOXO4-DRI', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Senolytic peptide that selectively triggers death of senescent ("zombie") cells in research.',
      mechanism: 'A modified FOXO4 peptide that disrupts the FOXO4–p53 interaction inside senescent cells, pushing those cells into apoptosis while sparing healthy cells.',
      benefits: ['Selectively clears senescent cells (animal data)', 'Studied for tissue rejuvenation'],
      dosing: { dose: 'Not established', frequency: 'Intermittent (research)', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: 'Pulsed courses (research)', range: 'No human protocol', notes: 'Preclinical; senolytics are typically dosed in short intermittent pulses in studies.' },
      sideEffects: ['Unknown in humans'],
      warnings: ['No human safety data', 'Not medical advice'],
    },
    {
      slug: 'dsip', name: 'DSIP', category: 'anti_aging', phase: 'Preclinical', aka: ['Delta Sleep-Inducing Peptide'],
      overview: 'Sleep-promoting peptide that may enhance deep sleep without suppressing REM.',
      mechanism: 'A neuromodulatory peptide that may promote delta-wave (deep) sleep and has been studied for stress, pain, and hormonal regulation.',
      benefits: ['May improve deep-sleep quality', 'Studied for stress resilience', 'Possible mild analgesic effect'],
      dosing: { dose: '100–300 mcg', frequency: 'Nightly as needed', route: 'Subcutaneous injection', timing: 'Before bed', food: 'Any', duration: 'As needed', range: '100–500 mcg', notes: 'Used in anecdotal sleep protocols; human data limited.' },
      sideEffects: ['Injection-site reactions', 'Grogginess', 'Headache'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'glutathione', name: 'Glutathione', category: 'anti_aging', phase: 'Phase 2', aka: ['GSH'],
      overview: 'The body\u2019s master antioxidant — critical for detoxification, immune function, and cellular protection.',
      mechanism: 'A tripeptide (glutamate-cysteine-glycine) that neutralizes free radicals, recycles other antioxidants, and supports liver detoxification pathways.',
      benefits: ['Master antioxidant / detox support', 'Immune and liver support', 'Studied for skin brightening (IV)'],
      dosing: { dose: '200–600 mg', frequency: 'Daily to weekly', route: 'Oral, IV, or subcutaneous', timing: 'Any', food: 'Any', duration: 'Ongoing', range: 'Varies by route', notes: 'IV/injectable and liposomal forms bypass poor oral absorption.' },
      sideEffects: ['Generally well tolerated', 'Possible bloating (oral)'],
      warnings: ['Caution with asthma (inhaled forms)', 'Not medical advice'],
    },
    {
      slug: 'carnosine', name: 'Carnosine', category: 'anti_aging', phase: 'Phase 2',
      overview: 'Anti-glycation dipeptide that helps protect proteins from age-related damage.',
      mechanism: 'A beta-alanine/histidine dipeptide that buffers acid, scavenges reactive carbonyls, and inhibits glycation (sugar-driven protein damage).',
      benefits: ['Anti-glycation/antioxidant protection', 'Muscle-buffering during exercise', 'Studied for cognitive and eye health'],
      dosing: { dose: '500–1,000 mg', frequency: '1–2× daily', route: 'Oral', timing: 'Any', food: 'With or without', duration: 'Ongoing', range: '500–2,000 mg/day', notes: 'Sold as an oral supplement; beta-alanine is a common precursor strategy.' },
      sideEffects: ['Tingling (paresthesia) at high doses', 'Mild GI upset'],
      warnings: ['Generally well tolerated', 'Not medical advice'],
    },
    {
      slug: 'vilon', name: 'Vilon', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Thymic bioregulatory dipeptide studied for immune-system rejuvenation.',
      mechanism: 'A short Khavinson bioregulator (Lys-Glu) proposed to influence gene expression supporting thymus and immune-cell function.',
      benefits: ['Studied for immune rejuvenation', 'Part of the bioregulator peptide family'],
      dosing: { dose: '~5–10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Any', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Russian bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'bronchogen', name: 'Bronchogen', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Bioregulatory peptide targeting respiratory-tissue repair and lung health.',
      mechanism: 'A short bioregulator peptide proposed to support bronchial epithelium maintenance and repair via gene-expression effects.',
      benefits: ['Studied for respiratory-tissue support'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Any', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'chonluten', name: 'Chonluten', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Bioregulatory peptide for GI and respiratory mucosal-tissue maintenance.',
      mechanism: 'A short bioregulator tripeptide proposed to support mucosal epithelial tissue of the gut and airways.',
      benefits: ['Studied for mucosal-tissue support', 'Antioxidant/protective signaling'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Any', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'livagen', name: 'Livagen', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Liver-targeting bioregulatory peptide studied for hepatic cell renewal.',
      mechanism: 'A short bioregulator peptide proposed to support liver-cell function and chromatin activation in hepatic tissue.',
      benefits: ['Studied for liver-tissue support'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Any', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'pancragen', name: 'Pancragen', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Pancreas-targeting bioregulatory peptide studied for beta-cell support.',
      mechanism: 'A short bioregulator peptide proposed to support pancreatic-tissue function and carbohydrate metabolism.',
      benefits: ['Studied for pancreatic-tissue support'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Any', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'testagen', name: 'Testagen', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Testicular bioregulatory peptide for male reproductive-health maintenance.',
      mechanism: 'A short bioregulator peptide proposed to support testicular-tissue function and reproductive-hormone regulation.',
      benefits: ['Studied for male reproductive-tissue support'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular (research)', timing: 'Any', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },
    {
      slug: 'prostamax', name: 'Prostamax', category: 'anti_aging', phase: 'Preclinical',
      overview: 'Prostate-targeting bioregulatory peptide for age-related prostate health.',
      mechanism: 'A bioregulator peptide complex proposed to support prostate-tissue function and reduce age-related inflammation.',
      benefits: ['Studied for prostate-tissue support'],
      dosing: { dose: '~10 mg', frequency: 'Daily in courses', route: 'Intramuscular/oral (research)', timing: 'Any', food: 'Any', duration: '10-day courses', range: 'Per protocol', notes: 'Bioregulator peptide; limited Western data.' },
      sideEffects: ['Injection-site reactions'],
      warnings: ['Limited human data', 'Not medical advice'],
    },

    /* ─── HORMONAL ───────────────────────────────────────────────────────── */
    {
      slug: 'pt-141', name: 'PT-141', category: 'hormonal', phase: 'FDA Approved', aka: ['Bremelanotide', 'Vyleesi'],
      overview: 'FDA-approved for hypoactive sexual desire disorder; works through brain melanocortin pathways.',
      status: 'FDA-approved (Vyleesi) for premenopausal HSDD.',
      mechanism: 'Melanocortin-receptor (MC4R) agonist that acts centrally on sexual-desire pathways rather than on blood flow.',
      benefits: ['Increases sexual desire/arousal in both sexes (research)', 'Centrally acting — not a vasodilator'],
      dosing: { dose: '1.75 mg (approved) / lower in research', frequency: 'As needed before activity', route: 'Subcutaneous injection', timing: '~45 min before activity', food: 'Any', duration: 'As needed', range: '0.5–1.75 mg', notes: 'Start low to gauge nausea tolerance.' },
      sideEffects: ['Nausea', 'Flushing', 'Headache', 'Transient blood-pressure rise'],
      warnings: ['Avoid with uncontrolled hypertension/CV disease', 'May darken skin/moles with repeated use', 'Not medical advice'],
    },
    {
      slug: 'melanotan-ii', name: 'Melanotan II', category: 'hormonal', phase: 'Preclinical',
      overview: 'Melanocortin agonist for tanning and sexual function, with significant safety concerns.',
      mechanism: 'Non-selective melanocortin-receptor agonist that stimulates melanin production (tanning) and central sexual-arousal pathways.',
      benefits: ['Stimulates skin tanning', 'Libido/erectile effects'],
      dosing: { dose: '250–500 mcg', frequency: 'Daily (loading), then 2–3× weekly', route: 'Subcutaneous injection', timing: 'Any', food: 'Any', duration: 'Loading then maintenance', range: '250 mcg–1 mg/day', notes: 'Sun exposure still required for tanning; start low for nausea.' },
      sideEffects: ['Nausea', 'Facial flushing', 'Darkening of moles/freckles', 'Spontaneous erections'],
      warnings: ['Unregulated; quality varies widely', 'Monitor skin/moles (melanoma concern)', 'Not medical advice'],
    },
    {
      slug: 'kisspeptin', name: 'Kisspeptin', category: 'hormonal', phase: 'Phase 2',
      overview: 'Master upstream regulator of reproductive hormones; triggers natural GnRH release.',
      mechanism: 'Stimulates hypothalamic GnRH neurons, the top of the reproductive hormone cascade, increasing downstream LH/FSH and sex-hormone production.',
      benefits: ['Triggers natural reproductive-hormone release', 'Studied for fertility and low libido', 'May aid testing of reproductive function'],
      dosing: { dose: 'Research-stage', frequency: 'Varies', route: 'Subcutaneous/IV (research)', timing: '—', food: '—', duration: 'Investigational', range: 'No standard protocol', notes: 'Mostly studied in fertility research; no consumer dosing standard.' },
      sideEffects: ['Generally well tolerated in trials', 'Injection-site reactions'],
      warnings: ['Investigational', 'Not medical advice'],
    },
    {
      slug: 'oxytocin', name: 'Oxytocin', category: 'hormonal', phase: 'FDA Approved',
      overview: 'The "bonding hormone," FDA-approved for labor induction; researched for mood and social bonding.',
      status: 'FDA-approved (Pitocin) for obstetric use.',
      mechanism: 'A hypothalamic peptide hormone that drives uterine contraction and milk letdown, and centrally influences social bonding, trust, and mood.',
      benefits: ['Obstetric use (labor/lactation)', 'Studied for social bonding and mood', 'Researched for anxiety/relationship effects'],
      dosing: { dose: 'Clinical (obstetric) / research intranasal', frequency: 'Varies', route: 'IV (obstetric) or intranasal (research)', timing: '—', food: 'Any', duration: 'Per use', range: 'Per indication', notes: 'Obstetric dosing is strictly clinical; intranasal social/mood use is investigational.' },
      sideEffects: ['Nausea', 'Headache', 'Blood-pressure/heart-rate changes (IV)'],
      warnings: ['Obstetric use is clinical only', 'Not medical advice'],
    },
    {
      slug: 'gonadorelin', name: 'Gonadorelin', category: 'hormonal', phase: 'FDA Approved',
      overview: 'FDA-approved GnRH agonist used to maintain natural testosterone production, often alongside TRT.',
      status: 'FDA-approved.',
      mechanism: 'Stimulates pituitary LH/FSH release, supporting testicular function; mimics natural GnRH pulses.',
      benefits: ['Maintains testicular function/fertility on TRT', 'Stimulates natural LH/FSH', 'Alternative to hCG'],
      dosing: { dose: '100–200 mcg', frequency: '2–3× weekly (or more)', route: 'Subcutaneous injection', timing: 'Any', food: 'Any', duration: 'Ongoing with TRT', range: 'Per prescriber', notes: 'Often replaces hCG for maintaining fertility/testicular size on TRT; short half-life.' },
      sideEffects: ['Injection-site reactions', 'Headache', 'Hormonal fluctuations'],
      warnings: ['Use under medical supervision', 'Not medical advice'],
    },
    {
      slug: 'follistatin', name: 'Follistatin', category: 'hormonal', phase: 'Preclinical',
      overview: 'Myostatin inhibitor researched for muscle growth.',
      mechanism: 'Binds and inhibits myostatin (a brake on muscle growth) and related TGF-β proteins, potentially allowing greater muscle development.',
      benefits: ['Inhibits myostatin (muscle-growth research)', 'Studied for muscle-wasting conditions'],
      dosing: { dose: 'Research-stage', frequency: 'Varies', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: 'Investigational', range: 'No standard protocol', notes: 'Largely gene-therapy/research context; consumer peptide quality and efficacy are uncertain.' },
      sideEffects: ['Unknown long-term effects'],
      warnings: ['Investigational; theoretical tumor-growth concern', 'Not medical advice'],
    },
    {
      slug: 'triptorelin', name: 'Triptorelin', category: 'hormonal', phase: 'FDA Approved', aka: ['Trelstar'],
      overview: 'GnRH agonist used for hormone suppression; FDA-approved for advanced prostate cancer.',
      status: 'FDA-approved.',
      mechanism: 'Long-acting GnRH agonist that, after an initial surge, downregulates pituitary receptors to suppress sex-hormone production.',
      benefits: ['Suppresses testosterone (prostate cancer)', 'Used for endometriosis/precocious puberty abroad'],
      dosing: { dose: '3.75 mg (monthly depot) etc.', frequency: 'Monthly to 6-monthly depot', route: 'Intramuscular depot', timing: 'Per schedule', food: 'N/A', duration: 'Per prescriber', range: 'Depot formulations', notes: 'Prescription depot medication; clinical use only.' },
      sideEffects: ['Hot flashes', 'Initial testosterone flare', 'Bone-density loss (long-term)'],
      warnings: ['Prescription only', 'Not medical advice'],
    },
    {
      slug: 'nafarelin', name: 'Nafarelin', category: 'hormonal', phase: 'FDA Approved', aka: ['Synarel'],
      overview: 'Intranasal GnRH agonist, FDA-approved for endometriosis and central precocious puberty.',
      status: 'FDA-approved.',
      mechanism: 'Intranasal GnRH agonist that suppresses sex-hormone production after initial stimulation.',
      benefits: ['Treats endometriosis', 'Treats central precocious puberty', 'Needle-free (nasal)'],
      dosing: { dose: '200 mcg per spray', frequency: '1–2× daily', route: 'Intranasal', timing: 'Per schedule', food: 'N/A', duration: 'Per prescriber', range: '400–800 mcg/day', notes: 'Prescription medication.' },
      sideEffects: ['Hot flashes', 'Nasal irritation', 'Mood changes'],
      warnings: ['Prescription only', 'Not medical advice'],
    },
    {
      slug: 'buserelin', name: 'Buserelin', category: 'hormonal', phase: 'Phase 3', aka: ['Suprefact'],
      overview: 'GnRH agonist for hormone suppression; approved outside the US.',
      status: 'Approved in several countries; not FDA-approved.',
      mechanism: 'GnRH agonist that suppresses sex-hormone production; used in prostate cancer, endometriosis, and assisted reproduction.',
      benefits: ['Hormone suppression', 'Used in IVF protocols abroad'],
      dosing: { dose: 'Per protocol', frequency: 'Daily (nasal/SubQ) or depot', route: 'Intranasal, subcutaneous, or depot', timing: 'Per schedule', food: 'N/A', duration: 'Per prescriber', range: 'Per indication', notes: 'Prescription medication abroad.' },
      sideEffects: ['Hot flashes', 'Initial flare', 'Nasal irritation (nasal form)'],
      warnings: ['Not FDA-approved', 'Not medical advice'],
    },
    {
      slug: 'degarelix', name: 'Degarelix', category: 'hormonal', phase: 'FDA Approved', aka: ['Firmagon'],
      overview: 'GnRH antagonist providing rapid testosterone suppression without an initial flare; FDA-approved.',
      status: 'FDA-approved (Firmagon) for prostate cancer.',
      mechanism: 'GnRH receptor antagonist that immediately blocks the receptor, suppressing testosterone rapidly without the testosterone surge seen with agonists.',
      benefits: ['Rapid testosterone suppression', 'No initial flare', 'Prostate-cancer treatment'],
      dosing: { dose: '240 mg loading → 80 mg', frequency: 'Monthly maintenance', route: 'Subcutaneous depot', timing: 'Per schedule', food: 'N/A', duration: 'Per prescriber', range: 'Depot dosing', notes: 'Prescription medication; clinical use only.' },
      sideEffects: ['Injection-site reactions', 'Hot flashes', 'Weight gain'],
      warnings: ['Prescription only', 'Not medical advice'],
    },
    {
      slug: 'bremelanotide', name: 'Bremelanotide', category: 'hormonal', phase: 'FDA Approved', aka: ['PT-141', 'Vyleesi'],
      overview: 'Generic name for PT-141 — an MC4R agonist for sexual-desire disorders.',
      status: 'FDA-approved (Vyleesi) for premenopausal HSDD.',
      mechanism: 'Melanocortin (MC4R) agonist that acts on central sexual-desire pathways; the approved formulation of PT-141.',
      benefits: ['Increases sexual desire (HSDD)', 'Centrally acting'],
      dosing: { dose: '1.75 mg', frequency: 'As needed before activity', route: 'Subcutaneous injection', timing: '~45 min before activity', food: 'Any', duration: 'As needed (max ~8/month)', range: '1.75 mg/dose', notes: 'Same molecule as PT-141.' },
      sideEffects: ['Nausea', 'Flushing', 'Headache', 'Transient BP rise'],
      warnings: ['Avoid with uncontrolled hypertension/CV disease', 'Not medical advice'],
    },

    /* ─── METABOLIC ──────────────────────────────────────────────────────── */
    {
      slug: '5-amino-1mq', name: '5-Amino-1MQ', category: 'metabolic', phase: 'Preclinical',
      overview: 'NNMT inhibitor that boosts NAD+ for fat metabolism without affecting appetite.',
      mechanism: 'Blocks the enzyme NNMT in fat cells, raising cellular NAD+ and SAM and promoting fat-cell metabolism — without acting on appetite.',
      benefits: ['Promotes fat-cell metabolism', 'Raises NAD+', 'Does not suppress appetite'],
      dosing: { dose: '50–150 mg', frequency: 'Once daily', route: 'Oral', timing: 'Morning', food: 'With or without', duration: '8–12 weeks', range: '50–150 mg/day', notes: 'Oral small molecule; human data limited.' },
      sideEffects: ['Generally well tolerated in early use', 'Possible mild GI effects'],
      warnings: ['Preclinical/early data', 'Not medical advice'],
    },
    {
      slug: 'aicar', name: 'AICAR', category: 'metabolic', phase: 'Phase 2',
      overview: 'AMPK activator known as an "exercise mimetic" for its effect on endurance capacity.',
      mechanism: 'Activates AMPK, the cell\u2019s energy sensor, shifting metabolism toward fat oxidation and mitochondrial biogenesis — mimicking some effects of exercise.',
      benefits: ['Activates AMPK ("exercise mimetic")', 'May enhance endurance/fat oxidation', 'Studied for metabolic disorders'],
      dosing: { dose: 'Research-stage', frequency: 'Varies', route: 'Subcutaneous/IV (research)', timing: '—', food: '—', duration: 'Investigational', range: 'No standard human protocol', notes: 'High doses are used in research; WADA-prohibited in sport.' },
      sideEffects: ['Possible elevated uric acid', 'GI upset'],
      warnings: ['WADA-prohibited', 'Investigational', 'Not medical advice'],
    },
    {
      slug: 'adipotide', name: 'Adipotide', category: 'metabolic', phase: 'Preclinical',
      overview: 'Vascular-targeting peptide that destroys the blood supply to fat tissue in animal models.',
      mechanism: 'A pro-apoptotic peptide that targets the blood vessels feeding white fat tissue, causing fat-cell death by cutting off their blood supply in animal studies.',
      benefits: ['Rapid fat loss in animal models'],
      dosing: { dose: 'Not established', frequency: '—', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: '—', range: 'No human protocol', notes: 'Preclinical only; significant toxicity observed.' },
      sideEffects: ['Kidney toxicity in primate studies', 'Dehydration'],
      warnings: ['Significant toxicity concerns (kidney)', 'Preclinical only', 'Not medical advice'],
    },
    {
      slug: 'tesofensine', name: 'Tesofensine', category: 'metabolic', phase: 'Phase 3',
      overview: 'Triple monoamine reuptake inhibitor researched for appetite suppression and thermogenesis.',
      status: 'Phase 3. Not FDA-approved.',
      mechanism: 'Inhibits reuptake of noradrenaline, dopamine, and serotonin, reducing appetite and modestly increasing energy expenditure.',
      benefits: ['Significant appetite suppression in trials', 'Notable weight loss in Phase 2'],
      dosing: { dose: '0.25–0.5 mg', frequency: 'Once daily', route: 'Oral', timing: 'Morning', food: 'With or without', duration: 'Investigational', range: '0.25–1 mg/day (trials)', notes: 'Investigational; cardiovascular and mood effects monitored in trials.' },
      sideEffects: ['Increased heart rate/BP', 'Insomnia', 'Dry mouth', 'Mood changes'],
      warnings: ['Investigational', 'Cardiovascular/mood caution', 'Not medical advice'],
    },
    {
      slug: 'setmelanotide', name: 'Setmelanotide', category: 'metabolic', phase: 'FDA Approved', aka: ['Imcivree'],
      overview: 'MC4R agonist, FDA-approved for certain rare genetic forms of obesity.',
      status: 'FDA-approved for specific genetic obesity mutations.',
      mechanism: 'Activates the MC4R appetite-regulating pathway in the brain, restoring satiety signaling in people with specific genetic deficiencies upstream of MC4R.',
      benefits: ['Effective for rare genetic obesity (POMC, LEPR, etc.)', 'Reduces hunger in eligible patients'],
      dosing: { dose: '2–3 mg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Morning', food: 'Any', duration: 'Per prescriber', range: '1–3 mg/day', notes: 'Prescription medication for genetically confirmed indications.' },
      sideEffects: ['Skin hyperpigmentation', 'Injection-site reactions', 'Nausea', 'Spontaneous erections'],
      warnings: ['For confirmed genetic indications', 'Prescription only', 'Not medical advice'],
    },
    {
      slug: 'pegvisomant', name: 'Pegvisomant', category: 'metabolic', phase: 'FDA Approved', aka: ['Somavert'],
      overview: 'Growth-hormone receptor antagonist, FDA-approved for acromegaly; blocks excess GH action.',
      status: 'FDA-approved.',
      mechanism: 'A pegylated GH-receptor antagonist that blocks GH from acting, lowering IGF-1 in conditions of GH excess (acromegaly).',
      benefits: ['Normalizes IGF-1 in acromegaly', 'Controls GH-excess symptoms'],
      dosing: { dose: '10–30 mg', frequency: 'Once daily', route: 'Subcutaneous injection', timing: 'Any', food: 'Any', duration: 'Per prescriber', range: '10–30 mg/day', notes: 'Prescription medication; liver enzymes are monitored.' },
      sideEffects: ['Injection-site reactions', 'Liver-enzyme elevation', 'Headache'],
      warnings: ['Monitor liver function', 'Prescription only', 'Not medical advice'],
    },

    /* ─── PAIN & ANALGESIC ───────────────────────────────────────────────── */
    {
      slug: 'ziconotide', name: 'Ziconotide', category: 'pain', phase: 'FDA Approved', aka: ['Prialt'],
      overview: 'Non-opioid intrathecal analgesic derived from cone-snail venom, for severe chronic pain.',
      status: 'FDA-approved (Prialt) for intrathecal use.',
      mechanism: 'Blocks N-type calcium channels on pain-signaling neurons in the spinal cord, interrupting pain transmission without opioid receptors.',
      benefits: ['Powerful non-opioid analgesia', 'No tolerance/dependence like opioids', 'For severe refractory chronic pain'],
      dosing: { dose: 'Micrograms/day (titrated)', frequency: 'Continuous infusion', route: 'Intrathecal pump', timing: 'Continuous', food: 'N/A', duration: 'Per prescriber', range: 'Specialist-titrated', notes: 'Delivered only via an intrathecal pump in a specialist setting.' },
      sideEffects: ['Dizziness', 'Confusion', 'Nausea', 'Psychiatric symptoms at higher doses'],
      warnings: ['Boxed warning: severe psychiatric/neurological effects', 'Specialist intrathecal use only', 'Not medical advice'],
    },
    {
      slug: 'exendin-4', name: 'Exendin-4', category: 'pain', phase: 'Preclinical',
      overview: 'Gila-monster venom peptide (basis of exenatide) with emerging research in neuropathic pain.',
      mechanism: 'A GLP-1 receptor agonist (the natural peptide behind exenatide); GLP-1 signaling in the nervous system is being explored for neuroprotective and analgesic effects.',
      benefits: ['Emerging neuropathic-pain research', 'Neuroprotective signaling', 'Established metabolic activity (as exenatide)'],
      dosing: { dose: 'Research-stage for pain', frequency: 'Varies', route: 'Subcutaneous (research)', timing: '—', food: '—', duration: 'Investigational', range: 'No pain-specific protocol', notes: 'Approved metabolically as exenatide; pain use is investigational.' },
      sideEffects: ['Nausea', 'GI upset'],
      warnings: ['Investigational for pain', 'Not medical advice'],
    },
    {
      slug: 'damgo', name: 'DAMGO', category: 'pain', phase: 'Preclinical',
      overview: 'Selective mu-opioid receptor agonist peptide used as a laboratory research tool only.',
      mechanism: 'A highly selective mu-opioid receptor agonist used in laboratories to study opioid signaling; not developed as a therapeutic.',
      benefits: ['Research tool for opioid-receptor studies'],
      dosing: { dose: 'N/A', frequency: '—', route: 'Laboratory only', timing: '—', food: '—', duration: '—', range: 'Not for human use', notes: 'A research reagent — not intended for human use.' },
      sideEffects: ['N/A (not for human use)'],
      warnings: ['Research tool — not for human use', 'Not medical advice'],
    },
  ];

  const phaseBlurb = {
    'FDA Approved': 'FDA-approved for at least one indication.',
    'Phase 3': 'In or completed Phase 3 clinical trials. Not FDA-approved for general use.',
    'Phase 2': 'Studied in Phase 2 clinical research. Not FDA-approved.',
    'Phase 1': 'Early-stage (Phase 1) human research. Not FDA-approved.',
    'Preclinical': 'Preclinical — primarily animal/lab data. Not FDA-approved; human evidence limited.',
  };
  P.forEach(p => {
    p.aka = p.aka || [];
    if (!p.status) p.status = phaseBlurb[p.phase] || '';
    p.hasDetail = !!(p.mechanism || p.dosing || (p.benefits && p.benefits.length));
  });

  window.PEPTIDE_DATA = P;
})();
